### ISSUE TITLE
As a content editor, I want to filter people in the personography by creator or library member so I can look at a subset of the people based on the kind of data work I'm doing.

### ISSUE THREAD

**Issue by elspethgreen** [Princeton-CDH/mep-django#106]
To make it easier to separate library-associated people from book-associated people, a filter in the personography distinguishing members from creators would be very useful.  

## Notes for development
- Creator: anyone who is a creator of any type on an item
- Library member: someone with an account
- need a third category for people who are not creators and not library members 
- Anyone who is in more than one category should show up in both lists
- Suggested filter name: member/creator
- implement as a `SimpleListFilter` - https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.list_filter

**Comment by rlskoeser** [comment]
Documenting notes from @elspethgreen in an email:
> ...  we do have to make sure that if someone selects "members," they get a full list of members, including those who are also creators.  And vice versa: creators should return a full list of creators, including those who are also members.  
> The people who are not yet associated with an account--but are not creators--should, for these purposes, count as "members."  We need to be able to find them to figure out what their deal is, and delete/fix their records accordingly.

@elspethgreen : rather than include people without an account as members, we're going to add a third category for non-creator non-member people. That is much more straightforward based on the way the database is structured and it will keep the other queries simple and fast. Do you have a preference for what we call this? @thatbudakguy suggested "uncategorized".

**Comment by rlskoeser** [comment]
@elspethgreen : rather than include people without an account as members, we're going to add a third category for non-creator non-member people. That is much more straightforward based on the way the database is structured and it will keep the other queries simple and fast. Do you have a preference for what we call this? @thatbudakguy suggested "uncategorized".

**Comment by jkotin** [comment]
"Uncategorized" is fine with me!  Could you give me an example of a person that is 1/ not a creator, and 2/ not a member?

Thanks --

Josh

**Comment by rlskoeser** [comment]
@jkotin I think right now these are mistakes: records that were created but never got associated with a library account and activity.  Based on your current use of the database, this would eventually be an empty category once you've dealt with those records. 

If in future you want to document people in the database who were related or connected to library members but were not actually members themselves, they would show up as uncategorized.

**Comment by jkotin** [comment]
This sounds good to me!  Thank you --

**Comment by elspethgreen** [comment]
Hello!

I've noticed a few entries in "uncategorized" that are definitely creators.  Do you know why these might have been missed by the filter?  Were they entered incorrectly by the undergrad encoders?

"Livy" (dates 0-17)
"Henry Howard Surrey" (dates 1517-1547)

Additionally, I suspect that some of the people listed in "Uncategorized" who do not have mepIDs, yet do have VIAF entries, may also be rogue creators, but their dates do not make it obvious.

**Comment by thatbudakguy** [comment]
@elspethgreen I think the system doesn't know that those are creators because they don't have a `Creator` relationship to an `Item`. right now, the way that the person types are determined is:

has at least one `Account` = "member"
has a `Creator` relationship to at least one `Item` = "creator"
does not have a relationship to any `Account` or `Item` = "uncategorized"

I didn't find any `Item`s for which Livy is listed as a `Creator`, so that's probably why they aren't showing up.

**Comment by clmahoney** [comment]
This looks good to me!
