### ISSUE TITLE
As a content editor, I want to add relationships between people in the database so that I can document known associates.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#11]
- [x] include role name in display
- [x] allow search by mepID
- [x] check Hilda Doolittle display on test site (see comments)

Testing suggestions:
- [ ]  In the people edit form, open up relationships and search by mepID for a known person
- [ ]  Under relationships, search for someone whose title has been set by the import. It should be displayed for ease of visibility

Notes:

 The Hilda Doolittle example was, we think, behaving as expected, since Hilda was in `name` and Doolittle in `sort name`. If you have the full name in both (following the import), the search should behave as expected, but please feel free to double-check!

**Comment by clmahoney** [comment]
Does this section refer to the "relationship type" section? Or is associate different altogether? 
And is there a code for certain relationships?

**Comment by i-davis** [comment]
I just added, just to test, to Sylvia's personography file the relationship "partner" to Adrienne. Realized this means that Adrienne's personography file will not be automatically updated –– makes sense, since not all relations are reciprocal like that.

I mentioned that in the relationship notes section we could include things like the dates of a relationship & notes about it. Cate suggested that it would be excellent if persons could have timelines, like we could enter the dates of a relation into the relationship section, and then those dates could be correlated with whatever other dates were added to other sections, and you could see those bits of a person's life reflected. That seems like a possibility, if it is one, off in the far future. & like it may only be interesting for someone like Sylvia, about whom we have so much info and who's central to the archive. But I also wonder if we could have a timeline like that for subscriptions, where all the subscriptions are correlated in one timeline? (Apologies if this is one of those comments you've all already thought about, & better'n I could!)

**Comment by rlskoeser** [comment]
This feature includes the relationship type as well as the person relationships which are editable on the edit person form, as @i-davis notes.  You're correct that relationships are not symmetric - you can add the relationship both ways when it's important to document.  We do display the reverse relationships on the edit form so you can see both sets at once.

For now, I suggest putting any known dates or other details in the notes field.  We may decide to add them in a more structured way later.

I think we've already talked about a timeline for the library account events (subscription, borrowing, etc) - that will be easier to look at in an upcoming phase once we import that data.

**Comment by elspethgreen** [comment]
I'm not sure I understand your comment about displaying the reverse relationships--when I was inputting "Leo Stein" as Gertrude Stein's sibling just now, it seemed like I would have to specifically search and access his record to input the reciprocal relationship.  Did I miss something?

**Comment by rlskoeser** [comment]
Yes, if you want to document the reverse relationship, you do have to search and add it in the other direction.  

As a way to try to help keep those relationships consistent, we customized the person edit form to display a list of relationships _to_ the current person (so you can see relationships in both directions for the current person).  For example, here's what's displayed at the bottom of Leo Stein's edit page:
![screen shot 2017-08-14 at 3 47 01 pm](https://user-images.githubusercontent.com/691231/29288755-f0244db8-8107-11e7-958f-466d10cab9eb.png)

**Comment by elspethgreen** [comment]
Ah yes I see that now!  That's really helpful.

**Comment by elspethgreen** [comment]
Two questions came up as I was looking at the mess that is the 3 different "worthing" records.  

First, and I'm sure this will be rare, the mepID #wort seems to exist because we're not sure which Worthing the card actually belongs to (and it might have belonged to them both).  They are distinguished only in the logbooks, in which they were given IDs #worthing1 and #worthing2.  Would it be an abuse of the "associate" feature to add some kind of "identity" or "equals" relationship?  Usually if we had a case of 2 IDs for one person, we'd just combine the IDs, but I think it's worth preserving the 3rd, ambiguous ID here, especially since that's the one associated with the card.

Second, as I went to fill in a "spouse" relationship between Mr. and Mrs. Worthing, I realized that it was impossible to tell which "Worthing" was which from the search menu.  It just lists "Worthing" three times because none have first names.  I don't want to say that either of them is married to him/herself, or to the general #wort record.  

Would it be possible to search by mepID in the relationship field?  Or (maybe this is good idea generally) would it be possible to display "roleName" if a first name is not available?  Then those three indistinguishable Worthings would be displayed as "Worthing, Mrs." "Worthing, Mr." and "Worthing."

Oh no, and now I've noticed another thing.  Just to double-check what a normal, full record looks like in the "associate" feature, I tried to say that worthing2 was married to Hilda Doolittle.  When I searched "Doolittle," no records came up.  And when I searched "Hilda," ONLY "Doolittle" displayed itself in the search field.  What do you think is going on with this?

**Comment by rlskoeser** [comment]
The Worthing case is interesting!  It sounds like a reasonable idea to create a new person record and then associate it with the other two somehow. @jabauer might have suggestions for other ways to handle it.  Will this be easier to handle / make more sense once we incorporate logbook data?

Adding the roleName to the display sounds valuable, there are a lot of people with only one name.  Searching by mepID also seems reasonable.  I'll also check on the Hilda Doolittle display, I don't remember which field is used for display here.

**Comment by elspethgreen** [comment]
Great, thanks!

**Comment by rlskoeser** [comment]
Re-opening because we had a few small changes we wanted to make that I haven't done yet.  I'll let you know when they're implemented so you can test the changes.

**Comment by rlskoeser** [comment]
@elspethgreen however: if you're willing to live with the current version and add the refinements later so that we can move forward with this release, I'm certainly ok with that!  If so, please close this issue and create a new issue to document the refinements to be done later.

**Comment by elspethgreen** [comment]
Searched for Helen Baldwin by mepID and added her as a "friend" of Pierre Auger.
Titles seem to be showing up in the list of people.
