### ISSUE TITLE
As a content editor, I want to search items by database id so that I can easily find items using the identifiers in the CSV export or notes.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#110]

**Comment by elspethgreen** [comment]
This works well enough--it would be nice if searching "114" didn't turn up all item numbers that contain that sequence, but since there are never that many I think it's okay.  Especially since the partial search feature is so important for the other kinds of searches we do, and I imagine it might be tricky to have it apply a different logic only to numbers.
