### ISSUE TITLE
edit person urls

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#13]
As a content editor, I want to add URLs to a person record so I can document the person's wikipedia URL or other relevant websites.

**Comment by clmahoney** [comment]
Hi! I added a URL to Richard Arlington's page to see if I could do that, but I'm having trouble deleting that URL now -- it seems like the only option it gives me is to delete all of Arlington, not just the URL. If I try to delete it and save again, it says that I've left the URL spot blank (which I did, since I got rid of it).

**Comment by bwhicks** [comment]
Hi @clmahoney. This one is a bit of a quirk in Django/Grappelli inlines.hted

<img width="1404" alt="screenshot 2017-08-07 10 16 50" src="https://user-images.githubusercontent.com/17815297/29030781-2d85f99e-7b5a-11e7-8837-d3f9d630cc46.png">

I've highlighted the delete 'x' in an outline. Click that to mark that you want to delete the url, and then 'save' on the person record. It should then delete the any of them.

Sorry for any confusion on this.

**Comment by clmahoney** [comment]
When I do that I get this message and it worries me that I'm going to delete the whole thing: 

![screen shot 2017-08-09 at 2 27 15 pm](https://user-images.githubusercontent.com/16673934/29137666-1a1beb64-7d0f-11e7-923f-64502b384948.png)

But is that right?

**Comment by clmahoney** [comment]
Oh nevermind, I figured it out! I need to press the X and then save and continue!
