### ISSUE TITLE
Investigate reconciling book data against OCLC APIs (initial investigation)

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#181]
We want to reconcile books against OCLC API to determine how much information can be pulled in automatically and how much book data work needs to be done automatically.  Could also be useful for merging records.

Goal for the initial round: find OCLC URI for work or edition and add to the database record. (High probability matches only; we'll have to think about how we might handle possible matches and give the team a way to select the right one.) I was initially thinking we should target [OCLC work id](https://www.oclc.org/developer/develop/linked-data/worldcat-entities/worldcat-work-entity.en.html). 

We probably want to use [WorldCat Search](https://www.oclc.org/developer/develop/web-services/worldcat-search-api.en.html); we should use whatever information we have available in the database; use first known event associated with a book as a limit on publication date (i.e. pub date must be before first event). 

Regine suggested that we try to get the specific edition if possible, and fall back to the work if we can't get an edition. I think the URIs and data available for them are different enough that we might want to store both in the database.

Once we have URIs, we can use them for merging book records, populating data from OCLC, etc. And it will also allow for planning on what book data work must be done manually.

**Comment by bwhicks** [comment]
Adding some notes from my exploration with the WorldCat Search API:

- The bibliographic SRU can return a pretty detailed records formatted as MarcXML or Dublin Core. Both have the OCLC included so that constructing a URL is pretty trivial. Will need to parse out the actual records vs other parts of XML response potentially (?)
- Could easily include an attempt at finding a specific edition, then if no results, back off. Default groups similar editions and reduces confusion
- Some experiments with year and title were able to pin a single return record pretty easily; for work easiest would be to back off the year and then see if we get a high enough certainty (tbd threshold) for the broader work (not finding a specific entry for the broader work so much as search without edition specific info and matching a different edition?)

**Comment by thatbudakguy** [comment]
this is probably not relevant anymore since I imagine y'all have done more research now, but just chiming in to share that I wrote [some notes here](https://docs.google.com/document/d/1vovLQ5cI1X0KCpCnlSTBOAaOvW_7YOWq8CuY2Z_Uus0/edit?usp=sharing) when I was playing around with OCLC APIs in the context of maybe running OpenRefine reconciliation against them.

**Comment by thatbudakguy** [comment]
one other random thing that came up in conversation with Nikitas - the Princeton catalog offers lookup by OCLC ID. An example is this manuscript collection of Japanese Buddhist scrolls (https://catalog.princeton.edu/catalog/8181849), which has OCLC ID 902811484: you can access the page by adding the ID to the /oclc/ endpoint, i.e. https://catalog.princeton.edu/catalog/oclc/902811484. should make it easier to add "find this item in catalog" functionality to MEP for items that have been reconciled.

**Comment by rlskoeser** [comment]
Initial investigation is complete; will create a new task for continuing work.
