### ISSUE TITLE
As a user, I want to filter library members by birth year so that I can do generational comparison, such as looking at just members from the Lost Generation.

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#197]
# testing notes
## designs
[desktop](https://zpl.io/aR1n8en) / [tablet](https://zpl.io/V1NEdXX) / [mobile](https://zpl.io/2GyD4mj)

to test this, visit the [members search page](https://test-shakespeareandco.cdh.princeton.edu/members/).

Note: Birth year will eventually be part of the member drop down, but now its styling imitates membership dates precisely, so these instructions are very similar. I've adjusted them to reflect the realities of the birth year data.

- does the "birth year" filter visually match the designs, across all screens? resize your browser window to try it at smaller sizes.
- when the page loads, are the placeholder numbers in the two boxes of the filter populated? (note that one will be 1998; this is because of bad data that hasn't yet been fixed in the database).
- when you type into one of the boxes, you should see the results updated as soon as you type a valid 4-digit year. try typing into one box, waiting, then doing the other.
- if you type something that isn't a 4-digit year, **nothing should happen**.
- if you type a year into the first box that is _later_ than the year in the second box (or vice versa), **nothing should happen** since this is an invalid range.
- if something was typed into one of the boxes and you delete all of it, the form should update again.
- the member results should look correct based on the birth dates you enter.

**Comment by clmahoney** [comment]
- YES the the "birth year" filter visually match the designs across all screens
- YES when the page loads there are placeholder numbers populated in the two boxes of the filter 
- YES when I type into one of the boxes, I see the results updated as soon as I type a valid 4-digit year. Both boxes work. 
- YES, nothing happens if I type in something that isn't a 4-digit year
- YES, nothing happens if I type in a year into the first box that is later than the year in the second box 
- YES, if I type something into one box and delete it, the form updates 
- NO, the member results don't look correct, but I think that's because there is bad data in the system.  For example, if I enter "1950" in the first box and nothing in the second, I get "Carrol, Akrata" who has a "birth year" of 1982 (clearly should be 1882) and a death year of 1952. So 1950 is in there, but not as the birth year. I'll include some more examples in screenshots. ALSO, if I put "1890" as a birth year, I get results like Beauvoir, Simone who is born in 1908. 
![Screen Shot 2019-06-27 at 3 47 35 PM](https://user-images.githubusercontent.com/16673934/60296219-9e310b80-98f3-11e9-8e0e-c91f7523e27a.png)
![Screen Shot 2019-06-27 at 3 47 43 PM](https://user-images.githubusercontent.com/16673934/60296224-a0936580-98f3-11e9-932f-af252091c333.png)
![Screen Shot 2019-06-27 at 3 47 50 PM](https://user-images.githubusercontent.com/16673934/60296225-a1c49280-98f3-11e9-92b1-6239b1da44be.png)
![Screen Shot 2019-06-27 at 3 51 23 PM](https://user-images.githubusercontent.com/16673934/60296227-a2f5bf80-98f3-11e9-82be-b623c813d6ba.png)

**Comment by clmahoney** [comment]
This looks good!

**Comment by rlskoeser** [comment]
Documenting from the conversation on Slack: the reported failure in the earlier comment are all explained by errors in the data and/or expected behavior for one of the range fields left empty (in which case it acts as an open-ended range that either ends or starts at the date that is entered).
