### ISSUE TITLE
As a user, I want to see a chronological list of book-related activities for a single library member so that I can see the complete history of book interactions for that person.

### ISSUE THREAD

**Issue by rgmunson** [Princeton-CDH/mep-django#216]
# testing notes
## design links
[desktop](https://zpl.io/b64oopg) / [tablet](https://zpl.io/29w7jwA) / [mobile](https://zpl.io/boMev6v)

you can get here by clicking "activities" on any member detail page (the default is now this screen instead of the membership activities table). @rlskoeser and I have been testing with [gertrude stein](https://test-shakespeareandco.cdh.princeton.edu/members/stein-gertrude/borrowing/) because she has a lot of interesting events with partial dates, etc.

## questions

leave a comment about these below if you have thoughts.

- how/can we display context for generic events in this view? it's possible they will display with a title and a partial date or two and nothing else. is this OK?
- the design includes tooltips on some events that display the public notes (see desktop/tablet). should we try out something like this?

## checklist

note that some aspects of styles are not implemented fully yet - there's no sorting controls on mobile, and on tablet the left column is not sticky. also, there's no expand/contract mechanism for the mobile list layout, so there won't be any arrows yet.

 - check the appearance of the table against designs on all screens.
- you should be able to sort the table normally using the controls at the tops of columns.
- on tablet, you should be able to scroll around inside the table to see all of its contents.
- on mobile, the table should use the list layout. check that the arrangement is correct and that there's no overlap of items.
- look around for partial dates: they should be formatted correctly, and sorting should incorporate them in a predictable way.
- missing or unknown values should show as a hyphen on desktop/tablet.
- missing or unknown values shouldn't be shown at all on mobile.

# dev notes
- [x] create a new view duplicating `MembershipActivities` called `BorrowingActivities`
- [x] write tests for the `BorrowingActivities` view
- [x] create a new template duplicating `membership_activities.html` called `borrowing_activities.html`
- [x] add a url to the members urlconf that goes to the `BorrowingActivities` view
- [x] make partial dates in this view display using AP style
- [x] switch membership events to also use AP style dates
- [x] sort authors by sort name

doesn't encompass a fair amount of mobile behaviors - see #444 and #445

**Comment by rlskoeser** [comment]
Re-estimating to 2 based on work done for membership activity list.

**Comment by thatbudakguy** [comment]
re-estimating to 3 because of generalizing styles for table display.

**Comment by jkotin** [comment]
Excellent!

Some notes:

I'm looking at Killen.

1. Author sort: this should by author last name, not first name.
2. Is there a way to clear a sort, so the list goes back to its default order?
3. I don't think book titles should be centred. They should be left justified. The dates look OK centred because there is little variation in length.
4. Should the book titles be italicized? 
5. The question mark beside "category" should now become a link, no?

Looking at G. Stein:

1. Dates without years shouldn't come first on the chronological list.
2. The Stein confirms how important it is to be able to go back to a default list order.
3. Author sort needs to go in alpha by last name.

Looking at Sarraute:

1. Is the hyphen better than "NA" for "not available"?  I'm happy with the hyphen, but I want to use what's clearest.

@clmahoney would you test for mobile and tablet as well?

**Comment by jkotin** [comment]
Re: Questions:

1. how/can we display context for generic events in this view? it's possible they will display with a title and a partial date or two and nothing else. is this OK?

I think that's OK.

2. the design includes tooltips on some events that display the public notes (see desktop/tablet). should we try out something like this?

I think we should postpone this until we focus on the books. My sense is that public notes will refer to the book/item itself, and not the event. Is that right @clmahoney -- or do we have explanations about particular events?

**Comment by clmahoney** [comment]
@jkotin I think we intended to use the public notes field for both. In general, the public notes field will be where we tell our audience that a book is generic and could be one of however many similar titles, but it can also be where we explain why an event is tricky. We need first to decide what we're going to do with the "Tricky card" list in the drive, with cards that have difficult events. If we decide to display them, the pub notes field will be where we can explain them.

**Comment by clmahoney** [comment]
Tablet: tested with Alderman
- YES, the table matches the table design 
- YES, I am able to sort using the controls at the top. Like Josh said, the author sort should sort by Last name, not First as it does currently. Otherwise the other filters seem correct. 
- YES, I am able to move around inside the table (especially side to side) to see all of the contents within it. 
- YES, missing or unknown values have a hyphen on tablet

**Comment by clmahoney** [comment]
Mobile: tested with Bidoire
- NO, the design does not match the mobile display right now: I cannot see any filters at the top! See screenshot: 
![Image from iOS (6)](https://user-images.githubusercontent.com/16673934/69918522-f5a64b00-1440-11ea-8f35-2916d5118608.png)
- YES, everything is in list format. But the type should be capitalized ("Borrow" not "borrow")

**Comment by thatbudakguy** [comment]
@clmahoney I added a note at the top of the checklist mentioning the lack of sorting controls on mobile for the time being - that work will be tracked on #444 and won't be in this release since it's a little tricky.

regarding the lowercasing of type ("borrow" vs "Borrow") I think that was done to increase contrast with the title, so it doesn't appear to be part of the words in the title. however, the titles are italicized now, so it might not be as necessary. @gissoo do you have thoughts?

**Comment by rlskoeser** [comment]
@gissoo please respond to comments about book titles centered or left justified, italicized; resetting sort to default; hyphen vs NA.

FWIW, I like the idea of italicizing the titles in all views and not just mobile.

Good catch on author sort! We'll make a note to fix that.

We can look at adjusting the date sorting so dates without years aren't listed first, although nothing is immediately obvious to me about the right way to implement it. @jkotin could you elaborate on your reasoning for wanting unknown dates last instead of first?

**Comment by thatbudakguy** [comment]
@rlskoeser iirc using the non-partial date value (for sorting only) achieves this, because partial dates get stringified `None` which always sorts after numbers. it's kind of hacky, but if we wanted to do it, i think that's a quick way.

**Comment by rlskoeser** [comment]
Forgot to add: 

- changing the category question mark to a link will be handled in a separate issue. #456 
- I agree about holding off the book notes until later; my sense is that mostly notes are about the _books_ and not the _events_, and I think it would be simpler if we can keep it that way. It's not clear to me how valuable it is to make those notes available on a list page like this vs. just displaying them when you click through to the book detail page.

**Comment by rlskoeser** [comment]
> @rlskoeser iirc using the non-partial date value (for sorting only) achieves this, because partial dates get stringified `None` which always sorts after numbers. it's kind of hacky, but if we wanted to do it, i think that's a quick way.

@thatbudakguy wouldn't we get the 1900 date instead? I'm not sure which scenario we get a `None` value, and I don't think that's what we want to use anyway (it is indeed hacky). We can do it, I'm just having trouble thinking of a simple way that doesn't require more logic to check on every date whether or not the year is known or not before generating a sort value.

**Comment by gissoo** [comment]
@thatbudakguy @jkotin @rlskoeser @clmahoney 
1. Capitalizing "borrow": Since this terms has changed from "borrowed" to "borrow", I would suggest capitalizing it everywhere now, it anyway doesn't read like a sentence anymore since it's not a verb anymore.  
2. Left aligning titles: On this issue on the borrowing activities table, titles have always been left-aligned in the designs and on the link provided as well as for Killen, if not, they are supposed to be left-aligned. 
3. Italicizing titles: I would agree with italicizing titles on the tables on all devices. 
4. Resetting sort to default: Please let me think about this, will comment about it here separately.
5. Hyphen or "NA": "NA" could mean "Not applicable", which can be very confusing. If it's not available and we want to communicate that it's not available, can we be more clear? Not sure how much this matters, just please let's not make it too cluttered, an abbreviation would be helpful if there is a clear one.

**Comment by jkotin** [comment]
@gissoo this is helpful. Re: 5 -- let's keep the hyphen. I'm wary of over-complicating.  (I take back my suggestion!)

**Comment by thatbudakguy** [comment]
@jkotin the team discussed implementing the ability to clear a table sort and decided it's not worthwhile to implement right now, for a few reasons:

- the user can already see the active default sort (start date, ascending) when the page loads, which means they can return to that sort at any time by clicking it.
- tables exist to display sorted information and are customarily displayed in a sorted form. telling the user that this sort can be "cleared" is somewhat misleading, because some sort must always be active in order for the table to be meaningful (unlike filters, which _can_ be cleared).
- adding a button to the UI to reset sort to default doesn't mesh well with the current design of tables; it's not clear where/how to implement this without having it be awkward.

hope this makes sense - happy to discuss in detail.

**Comment by thatbudakguy** [comment]
as per discussion at 12/4 mtg. "borrowed" on mobile will become Borrow, and the "type" column will be changed to "activity".

**Comment by clmahoney** [comment]
Mobile: checked on Bidoire again
- YES, "borrow" is now "Borrow" 

Desktop: 
- YES, the "Type" column in the book table is now changed to "Activity"

**Comment by clmahoney** [comment]
Can I close this? Does JK need to look at anything more?
