### ISSUE TITLE
As a user, I want to see a chronological list of membership activities for a single library member so that I can see the complete subscription activity for that person.

### ISSUE THREAD

**Issue by rgmunson** [Princeton-CDH/mep-django#217]
## Notes for testing
When you select a member from the member list and go to their detail page, the activities tab should now be clickable and will take you to the membership activity list by default (for now). This page should display a table of all membership activities (subscriptions and reimbursements).
- events should be ordered chronologically by default
- the table heading should be clickable to re-order the events
- you should be able to click a table heading twice to sort in the reverse direction
- the icons should indicate the current sort column and order
- dates and durations should sort logically (i.e. duration should sort 3 months, 6 months, 1 year; look at Flecker for a good account to test this with)

If a member has no documented membership activity, you should see brief text to that effect and not an empty table. Examples to look at (no need to check all of these):
- Louis Aragon
- Cyrille Arvanon
- Baswick
- Sylvia Beach
- Walter Benjamin

Check how the page looks for members with lots of subscription activity. Examples:
- Pougaud
- Colens, Fernand
- Seurre, J
- Flecker

**Comment by clmahoney** [comment]
1) Members with lots of events
--> I checked Hemingway first, just because! (We Love Ernest, he loved Beach)
- Yes, the events are ordered chronologically 
- Yes, I could click through the tabs to re-order and also click to reverse. I first put in duration (shortest to longest, then longest to shortest), then tried start and end date. The only problem was with amount: when I did amount in largest to least, the renewals went 150, 20, 30, 50, 86. Same thing happened with Flecker: all the other tabs worked fine, but the amount was wonky: went 144, 16 (16 x 10 in a row), then 35, 48, 81, 81, 81. 9.69.6. Is this messed up or am I perhaps not taking price per month into account? 
- Yes, when I click a tab arrow it is highlighted in green to show me that I have it on

2) Members with no events
- Yes, there is text that says "No documented membership activity." Tried this on Baswick, Beach, and Benjamin.

**Comment by rlskoeser** [comment]
@clmahoney good catch! The amounts are sorting alphabetically rather than numerically. I'll flag it as needs work and add a fix.

**Comment by rlskoeser** [comment]
@clmahoney this is fixed and ready for testing again. 

I should have thought of this before, but please also check some accounts that include a reimbursement event: it should display and sort as negative. (Abreu, Simone (de Bretteville) is one example; you could look at reimbursement events in the admin to find others.)

**Comment by clmahoney** [comment]
- OK, I checked Flecker and Pougaud and was able to sort them by amounts, both increasing and decreasing -- it's working great! 
- I first checked D.S.S. Mackenzie, who has 3 reimbursements and 2 renewals. The reimbursements show a negative number, which is correct, and I'm able to sort it in increasing (-100, -100, -50, 20, 180) and decreasing (180, 20, -50, -100, -100) amounts. I tested C. Barton, too, who has 1 reimbursement and 1 subscription amount. It's sorting well too!
