### ISSUE TITLE
Name fields (first/last?)

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#23]
Would it make sense to have separate fields for first name and last name?

**Comment by rlskoeser** [comment]
@jkotin this was the initial approach that @jabauer designed in the database, but I couldn't figure out how to make it work with all the variation in names that you have in the XML personography - married names, pseudonyms, `<nameLink>` elements for de or du.  That's why we came up with the revised approach to have a full name and a sort (or authorized) name.

You can see more details in my comment on the import issue #9, where I documented the decisions that Jean and I made: https://github.com/Princeton-CDH/mep-django/issues/9#issuecomment-318420577

If you want to revisit and can help us come up with a way to handle all the variations currently in your data (or some way of simplifying how we handle names), we can look into it.

**Comment by jkotin** [comment]
Would it make sense for us to have a meeting in September (in person!) to discuss the interface of the database?  Will there be an opportunity to revise it?  The MEP team to could continue to test and compile notes about our experiences using it and then prepare a joint response for CDH.

Is it not possible to have a page for each person in the personography with different fields: e.g., first name, middle name, last name, birth name, pseudonym, title, etc.  There could also be a field for display name.  Sometimes name complications are obvious and well-documented: Bryher, e.g.  But sometimes birth/maiden/married names are not well-documented and are essential for identification and dating.

**Comment by rlskoeser** [comment]
We should definitely meet to discuss the interface, and we can absolutely refine it once your team has started using it and has a better sense of what your needs are.  

I'd like to have @jabauer weigh on the name fields question.  Any information that doesn't fit in the existing fields should go in the notes (you'll see I'm already putting some additional name information in the notes field on import).

**Comment by rlskoeser** [comment]
This needs to be addressed before we finalize the person import, because it affects how we map the various names in the xml into the database structure.

**Comment by jabauer** [comment]
Hi Josh.  One of the differences in moving from XML to a relational database is that some of the complexity you have in the names can be simplied from a data modeling perspective without losing any information.  What you will need is an in-house style for handling the many kinds of names possible in the system when entering them in the varchar FULL NAME field.  A few examples of how this could work:
FULL_NAME: Jacqueline Lee "Jackie" Bouvier Kennedy Onassis
SORT_NAME: Kennedy, Jackie
FULL_NAME: Marie-Joseph Paul Yves Roch Gilbert du Motier, Marquis de Lafayette
SORT_NAME: Lafayette, Marquis de
FULL_NAME: George Sand (Amantine Lucile Aurore Dupin)
SORT_NAME: Sand, George

We could add a display name field, if you'd like.  But the researcher assistants would have to enter it, since it might differ from the FULL_NAME and SORT_NAME
In that case you could also have:
DISPLAY_NAME: Jackie Kennedy Onassis
DISPLAY_NAME: Marquis de Lafayette
DISPLAY_NAME: George Sand

How does that sound?

**Comment by jkotin** [comment]
Hi Jean -- thank you for this note. Sorry for the delay in responding. I'm not quite sure what to recommend here.  One issue is that the names of some individuals change over time, usually due to marriage. Assume that Jackie Bouvier patronizes S&C under that name. Users will expect to know that Jackie Bouvier eventually became Jacqueline Kennedy, perhaps even during her time as a member of S&C.  Another issue is the relation between "display names" and the actual names on the cards: we should have a way to coordinate them, especially when displayed simultaneously on the MEP website.  I welcome your advice on these issues.  The most important thing: we don't lose information that's already in the XML personography about names.  A third issue: a lot of members do not have standard "full names" -- just a list of birth names, married names, nicknames, titles.  The famous people, thus, are comparatively easy to sort out.

When I was doing research on the personography, I'd see a name on a card: e.g., Jane Smith. I'd then do research using the name and address and other information on the card. I might then, if I was lucky, identify the actual Jane Smith, using an obituary for Jane Doe, nee Smith.  I'd then link to the obit in the notes, and use the "sort" identify to make "Smith" the primary name and "Doe" the secondary name.  Here's an actual (and relatively simple) example from the personography:

                <person xml:id="bald.he">
                    <persName>
                        <surname sort="2" type="birth">Green</surname>
                        <surname sort="1" type="married">Baldwin</surname>
                        <forename>Helen</forename>
                    </persName>
                    <birth>1864</birth>
                    <death>1963</death>
                    <sex value="F"/>
                    <nationality> key="us">United States of America</nationality>
                    <residence>
                        <address>
                            <name>Hotel Belmont</name>
                            <street>30 Rue de Bassano</street>
                            <postCode>75116</postCode>
                            <settlement>Paris</settlement>
                        </address>
                        <geo>48.869218, 2.297872</geo>
                    </residence>
                    <residence>
                        <address>
                            <name>Riviera Palace</name>
                            <street>39 Bd de Cimiez</street>
                            <postCode>06000</postCode>
                            <settlement>Nice</settlement>
                        </address>
                        <geo>43.714588, 7.271752</geo>
                    </residence>
                    <note>This is Mrs. James Mark Baldwin; her husband, VIAF is 32058149</note>
                </person>

So the card lists this person as Mrs. James Mark Baldwin. After some research, I learned that this person's first name was Helen and that her birth name was Helen Green. My sense is that in the final version of the website she should be listed as "Mrs. James Mark Baldwin (Helen Baldwin, nee Green)." But we should be able to find here, using a search function, by a variety of names. 

I'm happy to discuss this issue by phone or in person next week, when I'm back in Princeton.

Josh

**Comment by jabauer** [comment]
Hi Josh.  The idea for FULL_NAME is that it serves as the authorized name within the system, so it should contain all naming information we have available for the life of the person in question.  Use of maiden and married names (in order of marriage) has emerged as a feminist best practice in digital resources, so as to not obscure women's identities under the men they married.  Of course, if the only name we have is Mrs. Smith, then that's what we use.  So I think FULL_NAME and SORT_NAME will handle the naming issues for Phase II.  And we can add the DISPLAY_NAME if that helps with any confusion between FULL_NAME and SORT_NAME

**Comment by jkotin** [comment]
This all sounds right -- thank you Jean!
