### ISSUE TITLE
As a user, I want the card image list paginated so that I don't have to browse through all the cards at once.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#238]
## Notes for testing
Card list should have next and previous links for navigating to other chunks of results; you should be able to navigate and see the next set of results. 
There should also be a drop down with alpha-labels showing the sections of results, and you should be able to navigate between sections that way also.

**Comment by clmahoney** [comment]
- YES, I can use the NEXT and PREVIOUS buttons at the top of the page to skip to the next chunk of cards. So if I'm on Catel thru Colens and want to get to the next bunch, I press "next" and see displayed Collins thru Dent. AND I see that's what I'm going to get thanks to the "DISPLAYING" button. 
- YES, if I want to move more quickly through the cards, I can click the drop down DISPLAYING button and see the alpha-labels, and I can move through those. So if I click on the displaying "Parr - Potte" I will get to a page that starts with "Parrain" and ends with "Pottecher" 

QUESTION: for the alpha-labels, is there a character limit on what displays? Right now they seem mixed. I think a 3 character limit would look better. 
For example, there is "A - Bos" (why A? Why not "Abr"?)
"Kn - Leve"  (Why Kn and not "Kni"
"Pott - Rey," (note that there's a comma included here, which I think looks odd)
"Win - E" (this shouldn't end with "E") 
- Also, the last three cards go PAST "Z" which should be the last cards listed I would think, if we're sticking with alphabetical. 
![Screen Shot 2019-10-24 at 1 06 25 PM](https://user-images.githubusercontent.com/16673934/67508489-1cfa4300-f65f-11e9-95b5-771d912e8faf.png)

**Comment by clmahoney** [comment]
Tablet: 
- YES, I can use the NEXT and PREVIOUS buttons at the top of the page to skip to the next chunk of cards. 
- YES I can click the drop down DISPLAYING button and see the alpha-labels, and I can move through those.

**Comment by clmahoney** [comment]
Mobile: 
- YES, I can click through to NEXT and PREVIOUS buttons, but they're not listed here as next or previous. Just arrows. I imagine this is because the lack of room on the phone display. 
![IMG_0732](https://user-images.githubusercontent.com/16673934/67508763-a6117a00-f65f-11e9-9940-832b20c3e180.PNG)

- YES, I can use the DISPLAYING drop down menu to go through chunks of names

**Comment by thatbudakguy** [comment]
@clmahoney just a note on the sorting - the reason that there are different character lengths in the options is because we automatically add only enough characters that are needed to distinguish between pages. so, for example:
```
Abreu
Ably
Abbott
...
Hemingway
Harris
Ingrid
...
```

to distinguish between the top three, we need at least three characters (`Abr, Abl, Abb`) since the first two are the same. to distinguish between Hemingway and Harris we need only two (`He, Ha`) and between those two and Ingrid only one (`H, I`). there's no limit, and the sort will automatically use the minimum number of characters required to properly distinguish between the names at a page boundary.

hope this makes sense.

**Comment by clmahoney** [comment]
@thatbudakguy thanks for explaining! Makes a lot of sense
