### ISSUE TITLE
As a user, when I'm viewing a single card image I want to navigate to any card images associated with the same member so that I can see all of their borrowing activity in context.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#249]
## dev notes
- display thumbnails
- thumbnails are clickable
- thumbnail div is scrollable
-  next/previous nav buttons on tablet and mobile
# testing notes
[design link - all screens](https://zpl.io/2vk5m7n)

I tested mostly with killen, but feel free to try a couple of different members with different amounts of cards (just one card, a few, a lot, etc). please also try on a device with a touch screen in addition to one with a mouse to make sure you can scroll around/touch things and it still works.

to test this, go to the member's page, then choose "cards", then pick any card.
- you should see thumbnails for all of the other card underneath the current one you're looking at
- there should be a small indicator showing the number of the card you're on / the total number of cards
- cards other than the one you're currently looking at should have their images faded out slightly
- if you hover over another card's thumbnail it should brighten up
- the card you're currently looking at should have a green outline around its thumbnail
- you should be able to scroll around on the list of other card thumbnails and click any of them
- the next/previous arrows on either side of the current card should still work the same way

**Comment by rlskoeser** [comment]
Re-estimating to 3pts for work to handle the large variety of states and cases.

**Comment by clmahoney** [comment]
Desktop: I tried on Pauline Alderman (2 cards), Gabrielle Camerlynck-Guernier (6), and Hemingway (14) 
- YES, I see thumbnails for all the cards under the one I'm currently looking at
![Screen Shot 2020-02-22 at 2 09 46 PM](https://user-images.githubusercontent.com/16673934/75097905-fc46e900-557d-11ea-925c-5cc133d37042.png)
![Screen Shot 2020-02-22 at 2 11 26 PM](https://user-images.githubusercontent.com/16673934/75097909-0537ba80-557e-11ea-82d9-1730793a92f0.png)
- YES, there is a small #/total card indicator on the bottom right corner that shows where I am in relation to the total amount of cards
- YES, in the bottom list of all the cards, the card I'm on is highlighted/surrounded by green, while the cards I'm not on are faded slightly. 
- YES, when I hover over the other card thumbnails, it brightens so that I can see it more clearly
- YES, I can scroll sideways on the list of card thumbnails with my laptop's trackpad 
- YES, I can use the next/previous arrows as usual

**Comment by clmahoney** [comment]
Mobile: 
- YES to everything here too! Works great. Tried on Killen and Arvanon:
![IMG_1479](https://user-images.githubusercontent.com/16673934/75097996-349af700-557f-11ea-8fd6-409815d8bfd9.PNG)

![IMG_1478](https://user-images.githubusercontent.com/16673934/75097994-32389d00-557f-11ea-8266-f02ac329eb7b.PNG)

**Comment by clmahoney** [comment]
Tablet: 
- Everything looks great here too! Tried on Pourtales. 
![85110828_2757500921035763_55769360064577536_n](https://user-images.githubusercontent.com/16673934/75098128-78dac700-5580-11ea-8702-e1d94fb1fe8b.png)

**Comment by clmahoney** [comment]
This all looks great and works well. I'll assign it to Josh so he can sign off on the look of it.
