### ISSUE TITLE
Question 1

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#25]
My apology if the question is beside the point.

What is the advantage of the current system for entering nationalities and addresses -- as opposed to a more conventional system with discrete fields with drop-down options? For example, a more intuitive system might be simply to have fields for street, city, postal code, etc., like on an online form.

**Comment by rlskoeser** [comment]
The advantage here is to leverage a relational database for what it does best, which means we'll be able to easily query and filter on people with the same nationality or find people who used the same address.

I don't entirely understand your question about the fields for address entry.  These look like discrete fields to me - were you imagining something different?

<img width="1009" alt="screen shot 2017-08-15 at 10 12 38 am" src="https://user-images.githubusercontent.com/691231/29319538-5da49d4e-81a2-11e7-8f4b-14c86d5bdfd9.png">


Related to #15 .

**Comment by jkotin** [comment]
Sorry for not being clear, you're right.  I was wondering about the necessity of the two-stage approach. As it stands, the user clicks +, waits for the pop-up, and enters information.  I'm so used to a one-stage approach: fields in which one can enter text and save one by one, if desired.  But if the two-stage approach is necessary for functionality, I'm happy.  I think that as we test, we should look for ways to streamline. But what we have here is great.

**Comment by rlskoeser** [comment]
Thanks for clarifying - I see what you mean now, that the addresses have to be edited on a separate page from the person data.  I tried to figure out a way to make the addresses editable as an inline on the form, but we can't do that in the Django Admin interface because of the kind of relationship we're using.  

The person to address relationship is a "many to many" relationship, which means that multiple people can be associated with a single address, and we're not duplicating the same address for each person the way it is in the XML.  So, in a way, having to go to a separate form to edit the address is a feature - because it hopefully makes it clear that the address is potentially associated with more than one person; this is part of the reason that the people associated with an address are also displayed on the address form.

We can certainly think about ways to streamline the process and improve the interface.
