### ISSUE TITLE
Display logbook data with personography entrie

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#26]
Would it be possible to, in the future, to include information from the logbooks with each entry in the personography?  It would be helpful to have information ready-to-hand that might help differentiate (or equate) adam3 and adam2, for example. We might learn that the memberships for adam3 and adam2 overlap, indicating that they are separate people. Or we might discover evidence that they are the same person. It would also be helpful to have links to the cards in the personography.

**Comment by rlskoeser** [comment]
We will absolutely include logbook data once we import it - that's already planned for the next phase of development work once the initial version of the personography is tested and moves into production.

If you have ideas about how you would like to see that logbook data displayed, please describe what you want to see or what functionality you need so that I can plan the development work accordingly.   Perhaps we could include a brief listing of membership date ranges or type of membership on the person list display?

**Comment by rlskoeser** [comment]
Created #37 to address this request.
