### ISSUE TITLE
As a user, when I'm viewing a single item I want an easy way to find all card images associated with that item so I can see where it's referenced in the archival materials.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#264]
## test notes
When looking at individual book detail or circulation pages, you should see a card tab.
- check that card tab is present and works on both bibliography and circulation pages
- check the card tab for multiple books to see that the correct information is displayed
- a book card page should display card images with member names and event dates for the event related to that work
- cards should be ordered by date, oldest first
- if a book appears on a card more than once, the card should be listed multiple times (example: Rolland borrowed multiple volumes of _Pilgrimage_ on the same card)
- when you click on a card, it should take you to the card image detail view for that member and should highlight the event related to the work; test this with one of the examples that references the same work multiple times on the same card

## dev notes
- [x] add card list view + url for books
- [x] adapt members card gallery template and view for books
- [x] find cards based on events instead of manifest
- ~consolidate event footnotes so they all link to primary event object and not subclass~
- [x] add id and target style for work in book activity table
- [x] unit tests for view
- [x] unit test for footnote queryset filter method
~- [ ] correct anchor link placement so first entry is not hidden under sticky table header on small screens~ (can't fix)
- [x] fix missing padding on mobile for target event
- [x] sort unknown years last

**Comment by rlskoeser** [comment]
Implementing this without an existing card browse page to link to will probably require slight adjustments to the design (bringing it more inline with the member detail page); might also be more than 1 point.

**Comment by thatbudakguy** [comment]
> agree 227 is probably better to defer. let’s do 264 with member names only (no dates), move 227 to wishlist, and we can open a new issue later to add years to the display if we think that names aren’t sufficient.
<sub>[View in Slack](https://cdhprinceton.slack.com/archives/C2YJR4VF0/p1580937419014000)</sub>

**Comment by thatbudakguy** [comment]
moving out of wishlist; see above slack link. for now we will have this work (and look) exactly like the "cards" tab on member detail, except that the titles under the cards will be the name on the associated account.

**Comment by clmahoney** [comment]
- YES, if I go to a book detail page, I always see the card tab present on the far right no matter if I'm on the bibliography page or circulation page. 
Biblio: 
![Screen Shot 2020-05-07 at 10 46 05 PM](https://user-images.githubusercontent.com/16673934/81364829-9b2aae00-90b4-11ea-8a29-0b9707c0586f.png)
Circulation: 
![Screen Shot 2020-05-07 at 10 46 14 PM](https://user-images.githubusercontent.com/16673934/81364831-9ebe3500-90b4-11ea-9aac-cf91b251b54d.png)
- YES, I checked the card tab for four different books and it always looked like the right info was there, with the right cards called up
- YES, if I click the card tab for a book then I see all the card images (and the corresponding member name the card belongs to, as well as the date)
- YES, the cards are ordered by date with the oldest/earliest card as the first card on the top left and the newest/most recent card on the right: ex: 
![Screen Shot 2020-05-07 at 10 50 50 PM](https://user-images.githubusercontent.com/16673934/81365085-391e7880-90b5-11ea-9014-7ee7434c90da.png)
- YES, if the book is borrowed multiple times on the same member card, I see the card multiple times but with the different dates that the book was taken out. Ex: Rolland's many borrows of different vols of "Pilgrimage" in April of 1921: 
![Screen Shot 2020-05-07 at 10 53 06 PM](https://user-images.githubusercontent.com/16673934/81365215-88fd3f80-90b5-11ea-98a7-4cdef9dba260.png)
Ex: Potocki de Montalk borrowing multiple issues of "transition" in June of 1929: 
![Screen Shot 2020-05-07 at 10 54 55 PM](https://user-images.githubusercontent.com/16673934/81365328-c9f55400-90b5-11ea-89e5-d281e4e60b18.png)
- YES, when I click on one of the cards, it takes me to the card image detail view for that member and highlights the event related to the work, so that I can see where it falls in the list, allowing me to then scan upwards to the card image and understand better where to find it on the card itself! I tried with Rolland's Pilgrimages and Montalk's transition issues and it always highlighted the specific date I had picked, not confusing the two. 

One observation: this only has happened once, but when I was searching for the "Life and Letters of Emily Dickinson" on Leo Stein's card, when I clicked the card where the event took place it highlighted the event but it was soooo far up at the top of the screen that at first I couldn't see it was highlighted at all. I tried to take a screenshot of it: 
![Screen Shot 2020-05-07 at 10 47 36 PM](https://user-images.githubusercontent.com/16673934/81365478-396b4380-90b6-11ea-8245-d36bd5064f20.png)
--> if you look up at the very top there's the pale blue highlight but I almost missed it. I think this has something to do with the fact that the borrow is the FIRST on the card? I tried again with other books that appear first on the card and this happened every time. Not a big deal at all, but worth noting if you guys know how to fix it. (Or maybe it's just my small laptop screen's fault?)

**Comment by rlskoeser** [comment]
@clmahoney wow, good catch on that last one — it looks like it only happens on smaller screens with the event close enough to the top that the anchor link actually puts it at the top of the page. It's getting hidden under the table header row at the top of the page. I've run into this before, there should be a way to adjust the styles to push the anchor link so it clears the header.

@jkotin please still review and comment on anything else you find that needs to be changed, but don't close after you review — the display problem Cate found should be corrected before we close the issue.

**Comment by jkotin** [comment]
This looks wonderful!  Two notes, only the first of which might be relevant. 

1. On the page for _A Farewell to Arms_, an undated card (Monica Stirling) appears first. Ditto for the _Ulysses_ page.  (The cards have a month, but not a year.)

2. My expectation when using the feature: when I clicked on a card, I'd see a large version of the card, and not the list of items borrowed.  (I expected to be able to scroll down to see the list.) I also expected to be able to click on the large version of the card and browse all the cards from the previous page—i.e. the cards featuring the book I searched for. (I'm not confident that my expectations should be the design guide.  But it might be worth discussing the choices.)

Everything else looks perfect!

Using the feature has lead me to reconsider how we list Pilgrimage and Hail and Farewell.  I think the value of tracking the individual books might be higher than seeing all the books together in the series.  (Think of Harry Potter: should the books be together or separate?) I also think that we should include printing numbers for Ulysses only. It's the only book for which that information is relevant and the info would look great on the page as designed.

**Comment by rlskoeser** [comment]
@jkotin thanks for the feedback.

I understand what you mean in terms of expectations and seeing the card image. If you had to choose between seeing the card image and having the title highlighted in the activity page, which is more important to you?

@gissoo would you read Josh's comment #2 above and try the feature on the site and weigh in on how you think it should behave?

@jkotin in regards to comment 1: I think I have it configured to sort unknown dates last (although I'm not sure we have any completely unknown dates for book events); sorting unknown years last is more difficult, but I'll take another stab at it.

@jkotin regarding _Pilgrimage_ — I've been wondering about that as I've used the site. For Harry Potter and LotR I would definitely expect to see the individual titles separately. I think it would make more sense to see them separately. It does make more sense to me to split them out, but I have another motivation for splitting them out — the pages for books and people with more cards and more activities are slower to load, which will lead to a less enjoyable user experience for people (in some cases, if a page takes more than a few seconds to load people will just give up). Breaking up these series into individual titles will result in fewer pages like that on the site, which seems like a good thing to me in terms of site performance.

**Comment by jkotin** [comment]
Thank you @rlskoeser -- I would choose seeing the card image, but I'm open to different points of view here.  Thank you too about sorting dates with an unknown year last.

We are on the same page re: Pilgrimage.  It's actually easier to revert here than make all the other series into multivolume works.

**Comment by gissoo** [comment]
@rlskoeser @jkotin thanks for writing – here are my responses: 

>     2. My expectation when using the feature: when I clicked on a card, I'd see a large version of the card, and not the list of items borrowed.  (I expected to be able to scroll down to see the list.) >

On this particular part of the site (book cards), the page (for Monica Stirling) currently loads to view the highlighted row rather than the large card image. This is because this row of the borrow details for _"A Farewell to Arms"_ is the main point of the page, the reason this card of Monica Stirling exists in this book's card gallery is that one event that is highlighted, and since the list of events on this page can be very long it's useful to be directed to the highlighted section at first, users can scroll up and see the card at any time, but they might easily miss the highlighted part. 

>  I also expected to be able to click on the large version of the card and browse all the cards from the previous page—i.e. the cards featuring the book I searched for. (I'm not confident that my expectations should be the design guide.  But it might be worth discussing the choices.)
> 

I agree! However this is happening because cards are associated with people. In order to have an improved UX here the cards will need to **not** be associated with people on this page (which is structurally problematic), in which case the card image viewer page would be different than it is now. Because we added this feature (book card) pretty late and one of the only reasons it was decided to be in scope is that we didn't need to touch the card image viewer page and its data the UX for it was also not in scope. 

I hope this helps.

**Comment by rlskoeser** [comment]
@jkotin are you ok with this solution now that @gissoo has explained more?

Thank you @gissoo for addressing the second part of Josh's point which I forgot to answer — you explained it better than I would have!

**Comment by jkotin** [comment]
Thank you @gissoo and @rlskoeser. My worry is that users won't know to scroll up.  But I'm OK with signing off on this if you don't think that will be a problem.

Re: card browse. I understand. This might be something for long term wishlist.

**Comment by gissoo** [comment]
@jkotin Because of the style of pages on the site and the expectation it creates as far as the content that appear on the top on all pages I'm confident they will know to scroll up, this is a point that is useful to keep in mind as more users will be using the site, I'll keep it in mind.

**Comment by rlskoeser** [comment]
@clmahoney please test/review the changes I made based on the first round of testing:
- cards with partially known dates (unknown year) should sort last
- the mobile display for the selected title on the member card detail list has been corrected

Both @thatbudakguy and I looked at the problem you identified where the highlighted title shows under the sticky table header row, but we couldn't fix it (the typical solutions for this problem don't work with tables). We're going to have to live with this one, at least for now — but thanks for the careful testing and identifying the problem. I'll turn your  comment into a new issue to document the problem.

**Comment by clmahoney** [comment]
- YES, cards with unknown dates appear last in the display of all cards that have a certain work on them. I tested the two that Josh had checked: _A Farewell to Arms_ and _Ulysses._ Both had the unknown or partial dates at the end. Except something weird was happening with Ulysses in the book search: if I click the first Ulysses (1922) I get a page error. But then the next Ulysses (1934) is fine. I thought it would be that the test site didn't have updated info, but on the test site I only see one.

**Comment by clmahoney** [comment]
@rlskoeser what am I testing for with the mobile display?

**Comment by rlskoeser** [comment]
@clmahoney sorry I didn't document or screenshot the problem! I noticed that when there was a title highlighted, the spacing was off. (This is on the card detail page when you click through and a title is selected.) I think a basic sanity check that it looks ok would be enough here.

**Comment by clmahoney** [comment]
OK I checked and the spacing seems fine to me!
