### ISSUE TITLE
Bibliography

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#28]
I don't quite understand how to add footnotes/bibliography. When I try to add a footnote, I'm asked for "Source type," "Bibliographic note," and "Notes." When I click "Source type," I'm asked for "Name" and "Notes." Is there a simpler way to add reference links? Perhaps two fields: 1/ link or CMS-style citation to book or article; 2/ text field with relevant quote or reason for citation? The current system seems too complicated.

**Comment by rlskoeser** [comment]
Thanks for the feedback on this.  We're going to need @jabauer to weigh in on this one, since it's something she designed and also something we're using in the other projects.  However, we're thinking of turning it into a reusable component that anyone can use, so input on how to make it easier to use is valuable!

I think the source type would be something like manuscript, letter, book, webpage - whatever makes sense for the kind of content you're working with.  You'll probably only have a small number of source types, and you'll enter them once and not have to work with them much.  We could even think about preloading some common source types if that would be helpful.

The bibliography is another place where we're leveraging the relational database for what it does best - if you have a single source that you're using for a number of footnotes, this lets you enter the bibliographic information once and link it to all the footnotes from that resource.  (It will also make it trivial to get a list of all footnotes from a single source.)  It probably does mean there's a bit more overhead when you have a footnote from a unique source.

**Comment by jabauer** [comment]
@rlskoeser is correct on how the system is designed to be used.  It also gives you the added flexibility of indicating on any Note whether the source in question agrees or disagrees with what is in the database record.  If you would like to discuss it at our next in person meeting I'd be happy to do so.

**Comment by rlskoeser** [comment]
Closing, this is no longer relevant.
