### ISSUE TITLE
Membership timeline for detail page

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#308]

**Comment by gissoo** [comment]
The designs proposed for this are located in the S&Co drive > Development & Design > Data Visualizations > 2019-08-28 – SVG > Issue #308 – Membership timeline for detail page

The data visualizations consist of,
graphs that show an individual’s: 

- membership and borrowing activities from the beginning till the end of their activities
- all active years from 1919-1941 (no distinction between the logbooks and cards)
- all active years from 1919-1963 (no distinction between the logbooks and cards)

Total of 3 visualizations.

- Note: A sample data from one of the members was found and used to create this visualization.
- Based on our internal meetings with RSK and NB we will discuss our questions with Josh and try prototyping with D3.js + I will continue my research and design for mobile versions of these data visualizations. 
- We also internally discussed how inaccessible it is to extract the data we need (for instance for this data visualization it would be extremely useful to see the range of membership and borrowing activities for each member to help us make more meaningful and efficient decisions.
- We also discussed the fact that Josh might actually want the individual member graph to show their activities over 1919-1963 rather than any other timeline, therefore the third visualization has been created.
