### ISSUE TITLE
Rename 'sex' to 'gender' project-wide

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#324]
# testing notes
head to the [members list page](https://test-shakespeareandco.cdh.princeton.edu/members/) and open the "demographics" tab. check that:

- the "sex" facet is now called "gender"
- the options under "gender" now include "nonbinary"
- there is a new tooltip (blue question mark) here; you can hover over it for a suggestion about reading the upcoming analysis essay that will talk about gender
- when you edit people in admin, you can set "nonbinary" for gender

if you can, do this on tablet/mobile to make sure that the tooltip displays correctly on those devices too.

# dev notes

based on [research on other folks' approaches to this](https://docs.google.com/document/d/1XXmfUHjLz4icTxaxv59EX0BLgEyAb2mym5aSs93WF4s/edit?usp=sharing) we should no longer use the term 'sex' to refer to the assumed genders of historical people represented in MEP. we will need to:

- [x] replace the term 'sex' with 'gender' everywhere it appears, including docs
- [x] add an option for people to be nonbinary
- [x] create and run a migration, since the field name on `Person` will change
- [x] add a tool-tip to the gender filter with brief explanation and link to essay/doc
- [x] re-index, since the name of a field in solr will change
- [x] add note to DEPLOYNOTES

**Comment by thatbudakguy** [comment]
will complete this once deployed and migration/ re-index is done.

**Comment by clmahoney** [comment]
On desktop: 
- YES, I see the "gender" filter now in demographics tab instead of "sex"
- YES, there's a "nonbinary" category, so the list now reads: Female, Male, Nonbinary, Unknown
- YES, I can see the blue tooltip and if I hover it explains that I can learn more about gender in the Analysis section
- YES, when I go to edit people in the admin I can see that "Nonbinary" is an option now. See screenshot. 
![Screen Shot 2019-11-12 at 12 31 15 PM](https://user-images.githubusercontent.com/16673934/68695239-aad39a80-0548-11ea-84f5-1c47265c865c.png)

**Comment by clmahoney** [comment]
On mobile: 
- YES, I see the "gender" filter now in demographics tab instead of "sex" on Members page
- YES, there's a "nonbinary" category, so the list now reads: Female, Male, Nonbinary, Unknown
- YES, I can see the blue tooltip and if I hover it explains that I can learn more about gender in the Analysis section (see screenshot for all of the above): 
![Image from iOS](https://user-images.githubusercontent.com/16673934/68696027-300b7f00-054a-11ea-9987-350590730b36.png)
- YES, when I go to edit people in the admin I can see that "Nonbinary" is an option now. See screenshot.
![Image from iOS](https://user-images.githubusercontent.com/16673934/68696045-3b5eaa80-054a-11ea-90e9-2313797fc922.png)
