### ISSUE TITLE
As a content editor, when I'm viewing the list of people I want to see nationalities and number of associated addresses so I scan for records that need more data.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#33]
Part of #32 .

## Testing Notes

- `# Addresses` is not sortable in any meaningful way (a limitation of the Django interface), so it is provided as a visual indicator only.
- `Nationalities` will often by only one or two, so filtering it based on the name of the first nationality in the set associated with the person seemed helpful.

## Errata

The admin backend package we use has a known error such that if you use a field with many possible values like addresses, when sorting by that field an entry will appear multiple times (once for every associated value). This is purely visual, and it does not affect the underlying data or database.

**Comment by elspethgreen** [comment]
I see that basically there are blocks of the same nationality (United States, United Kingdom) but I'm not sure what determines the order in which these blocks appear.  Could it be alphabetical? (not super important, but might help with ease of use)
It's a little confusing that the nationalities don't "switch" so that "United States" is always listed first in the "United States" block, but I don't think that indicates an actual problem.

**Comment by bwhicks** [comment]
@elspethgreen This is a bit of a Django issue. It sorts by country name alphabetically in each case, but the names in the individual block will always be sorted by name for the person, but the overall sort will be based on the country names as a whole.

It's a bit confusing if you're not familiar with the way Django handles this kind of field in the admin (and its limitations), so by way of example: 

If you sort ascending, you'll get all the people with no nationality first, and then the 'block' of nationalities in the list view will line up with the sort for those that do have them. (i.e. Canada will be first in their list if they're Canada and United States).

If you sort descending, you'll start with people with nationalities set, but it will be out of sync in the blocks (i.e. United States will come first by sort order overall, but the individual block will still display 'Canada, United States'.)

There's not really a way to modify this behavior (beyond making it so that it lines up when sorting descending, but then it will be out of sync when ascending). 

Does this make (some) sense? I *think* ascending will be more useful once the database is populated.

**Comment by elspethgreen** [comment]
That makes sense!  I'll close the issue.
