### ISSUE TITLE
As a user, when I'm browsing members I want to see membership years that show gaps in activity so that I'm not misled by what appears to be a longer continuous membership.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#365]
## testing notes
On the members page, members should display multiple sets of years and year ranges instead of first and last dates. Check a variety of records to see that the years match the activity dates we have for that member.

Members with no known years should still be listed with the Membership Dates heading but with a - to indicate unknown dates.

## dev notes
Split member details implementation out into #526; this story only applies to member search results.  Display should be years only, and may require logic to abbreviate if too long.

Display list of year ranges on member list template (may need logic to condense if there are too many ranges).

**Comment by rlskoeser** [comment]
Simpler than anticipated, downgrading from 2pt to 1.

No member has enough distinct ranges to require the excerpting logic in Gissoo's design, so I didn't implement it. (I'm not sure there are even any that go to three lines.)

**Comment by clmahoney** [comment]
- YES, on the member search page I see that dates have gaps now. See M. Alexandre on the site now: 
![Screen Shot 2020-05-06 at 12 24 11 PM](https://user-images.githubusercontent.com/16673934/81202591-d6ce5680-8f94-11ea-9976-6cca36332eb3.png)
and on the test site: 
![Screen Shot 2020-05-06 at 12 24 17 PM](https://user-images.githubusercontent.com/16673934/81202612-dcc43780-8f94-11ea-805f-36e055b28cfd.png)
- But when I go to M. Alexandre's individual member page, the "range" is still there, not the gaps
Another good example of a member with a few gaps: Renee Antoine-May: on test site: 
![Screen Shot 2020-05-06 at 12 28 57 PM](https://user-images.githubusercontent.com/16673934/81202933-48a6a000-8f95-11ea-897b-614a92ca3d55.png)
- YES, if we don't know the membership dates we see "-", instead of nothing/blank. eFor example, Cauralles: 
![Screen Shot 2020-05-06 at 12 31 27 PM](https://user-images.githubusercontent.com/16673934/81203155-9a4f2a80-8f95-11ea-819e-c53c3751829c.png)
