### ISSUE TITLE
As a content editor, I want to see an indicator if a person has an account associated so that I can distinguish library members from others associated with the library.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#37]
Testing notes: 
- [x] - The list view for people should have a 'has_account' checkmark
- [x] - The detail view for an individual person should also display this below mep_id

**Comment by elspethgreen** [comment]
Spot-checked a few check-marked people, and they did indeed have accounts.

**Comment by clmahoney** [comment]
Me too!

**Comment by i-davis** [comment]
Me three; also added an account for a Mr. McGillicutty, & he showed up properly in the Personography, with a lovely green checkmark.

**Comment by elspethgreen** [comment]
I was playing around with the test site just now, and I wonder if this "has account" indicator is really doing what we want it to.  Elvira de Alvear is marked as not having an account--but she does, both in the cards, logbooks, and (I just checked) in the current database import.  Why isn't she flagged as having an account when listed in the personography?

**Comment by elspethgreen** [comment]
Also, on the off chance that someone has a card but isn't in the logbooks, would they be flagged as not having an account?  The card import should be able to override this.

Unless more useful flags would be "in logbooks" and "in cards," rather than "has account"?  Then anyone who was neither would be automatically inferred to have "no account."

**Comment by bwhicks** [comment]
@elspethgreen This is an import issue, not an interface issue, in this case. There are still a handful of events that (for reasons I'm working on currently) that aren't importing, and I suspect hers may be among them. (So thank you for helping me find a nice potential exemplar for the problem.)

**Comment by bwhicks** [comment]
@elspethgreen Now that I've gotten the import script more pinned down, I see that Elvira is a case where she in fact has a card, but no logbook entry (as best I can tell). The card import should create an account for her.

All of the events (barring the handful for which I need the team's input in #36) are importing, so the other stray missing accounts should be resolved.

**Comment by elspethgreen** [comment]
She does have a logbook entry: a subscription on 2/28/1929.  I did "find in files" in Oxygen and was able to find it--what do you think is going on?

**Comment by elspethgreen** [comment]
Maybe this has to do with the incomplete harmonization?  Alvear, Aldington, and Alderman (who are all in the logbooks, but not showing up as having accounts) all have logbook entries that are under non-harmonized MEP ids.

**Comment by bwhicks** [comment]
@elspethgreen Is there a list of non-harmonized mep ids? I was using MEP ids to tie people to their accounts, which is the problem with this case. (Also why I didn't see the account, as I was naively searching by MEP id.)

**Comment by bwhicks** [comment]
@elspethgreen Deleted previous comment because I hit on the larger issue here. Those people will have stub records under the unharmonized mepids and account names, but they'll need to be harmonized manually because I can't reliably import that. (i.e. typos or non-standard names in the logbook formats).

These will have to be manually harmonized by the team. For example, you could look up accounts with Alvear in them, and if they do appear to be Elvira de Alvear, you can then use the autocomplete to look up her proper person entry and then reassign the account. After that, you could safely delete the dud stub entry (in this case Miss Elvira de Alvear).

Any attempt to do this via the import would be inevitably lossy or produce erroneous results.

Does this make sense? If not let me know and I can clarify further.

**Comment by bwhicks** [comment]
As an example of what could go wrong: If there  were both an Elvira and Ed Alvear, and in the logbooks we hit one who just noted as E. Alvear, there's no reliable way to know by the text within the persName tag which one we have. 

If we guessed, we'd only have a 50/50 odds of being right. A human can probably deduce a bit more and make a sane decision there whereas the import script would introduce incorrect associations.

**Comment by elspethgreen** [comment]
Yes--I'm sorry if we were unclear, but I thought that the need for further manual harmonization was a known issue.  That is the reason I was asking earlier whether the stub "person" records would be created, so we could do what you're describing above.  

With regard to this particular issue (the check-mark appearing if the person has an account): if the reason that some don't show up is because of the incomplete harmonization, then it is not a systematic issue with import/the association script, and so I think this issue is resolved.

**Comment by bwhicks** [comment]
@elspethgreen Excellent, sorry for the confusion on my end. Could you mark it resolved then?
