### ISSUE TITLE
As a content admin, I want to view graphs showing an overview of library membership over time so that I can see how card and logbook data compares and so I can download an SVG to include in an essay.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#385]
## Notes for testing
If you go to `/members/graphs/` on the test site you'll see a page with graphs showing totals for members across the lending library dates.
- should see 4 different versions of the graph
- the legend for each should match what's displayed

**Comment by rlskoeser** [comment]
Notes from conversation with @thatbudakguy about moving the d3.js code out of the template:

Add timeline divs to the template; use data-series to indicate which data points should be rendered, e.g.
```
<div class="timeline" data-series="subscriptions borrows members">  </div>
```
Template should include the totals and a method call to draw the graphs, passing the total to the graph method, e.g. `renderGraphs(totals);`

That new `renderGraphs` method will find all timeline divs, parse the series options, and then call a method to draw the graph, passing the totals, the element where the svg should be added, and the options for which series to draw.



drawGraph({subscriptions: true, borrowers: true})

**Comment by thatbudakguy** [comment]
fwiw there's a different approach to the problem of passing data to the client that I have been trying out on the member detail map, which you could also use here - maybe a little simpler than writing the js as a function? works like this:

1. write a snippet that will only be rendered if we want to render the graphs (for members with no data, we want to avoid including d3 or other code at all, since it won't be used). this already exists and is called `member_graph.html`, but it can be shortened to:
```html
{% load render_bundle from webpack_loader %}
{# this will be accessible in the global scope via `declare` in .ts files #}
<script nonce="{{ request.csp_nonce }}">
    var timeline_data = {{ timeline|json }}
</script>
{# only load the timeline code bundle here, since we know we're rendering the map #}
{% render_bundle 'memberTimeline' %}
```

2. include that snippet in a conditional block in the main view template (also already done).
```
    ...
    {% if account_start %}
    <div class="timeline">
         .... (will be filled by d3)....
    </div>
    {% include 'people/snippets/member_graph.html' %}
    {% endif %}
    ...
```

3. important part: move all the timeline d3 code into its own webpack bundle (entrypoint) called something like `memberTimeline.ts`, and add typings for the timeline data local to that module. it would look like:
```ts
import { scaleTime, axisTop, select } from d3 // can import only the parts of d3 we need now

// this gives the module access to stuff we defined outside, in the template
declare const timelineData: {
    membership_activities: Array<object>, // needs a slightly more specific type but you get the point
    book_activities: Array<object>,
    activity_ranges: Array<object>,
}

// now you can do...
var axis = axisTop(x);
  var svg = select(".timeline").insert('svg', '.description')
        .attr('preserveAspectRatio', 'xMidYMid meet')
        .attr('viewBox', '0 0 905 ' + opts.viewBoxHeight)
        .attr('aria-label', 'Chart: Member Timeline')
        .attr('aria-described-by', 'member-timeline-desc')
        .attr('role', 'img')
        .attr('id', mode + '-timeline');

...

// etc
  svg.append('g')
      .attr('class', 'subscription-end')
    .selectAll('circle')
    .data(timelineData.membership_activities.filter(event => event.endDate))
    .join(
      enter => enter.append("circle")
        .attr('class', 'end-date')
        .attr('cx', function(d) {
          return x(new Date(d.endDate))
         })
        .attr('cy', 60)
        .attr('r', 3)
        .attr("fill", "black")
    )

```

the utility of this is that it makes the ts module fully aware of the typings of the data (because you define them), and also means you don't need to refactor the bulk of the code into a monolithic function because:
 - it already has the data it needs in the global scope
 - it doesn't have to look for a DOM element in which to render because it's only ever called _after_ the DOM is ready and we have data
 - it doesn't get called more than once per page anyway

**Comment by thatbudakguy** [comment]
one thing to note: in the snippet that exports the data into the global scope, we should try to keep the amount of js as low as possible (ideally just that one line defining `timelineData` or whatever it is). this code doesn't get transpiled and skips our js pipeline entirely, so I intentionally used `var` for backwards compatibility.

in the _typescript_, though, we're free to redeclare the data as `const`, because we don't want to mutate it (doing so should be an error) and our code will be transpiled into `var` if necessary.

**Comment by clmahoney** [comment]
- YES the four graphs look bomb! 
- YES, the legends match. 
- For "Members with active subscriptions" the legend is light grey. 
- For "Members with borrowing activity" the legend is light blue. My only question is why the legend text is different than the graph title text here. The graph is called "Members with borrowing activity" and the legend calls it "Members with book activity" - might this confuse people? 
- For "Subscriptions and borrowing activity" the legend is blue and grey
- For "Subscriptions, borrowing, and total numbers" the legend is light grey, blue, and dark grey. Same question tho: why is borrowing activity different than "book activity"

**Comment by rlskoeser** [comment]
@clmahoney good point about the titles! I threw this in as provisional markers - I don't really intend to share this url with people directly, planning to use this internally to export SVG images to include in the card/logbook relationship essay, but that's an easy fix that makes sense to do.

**Comment by clmahoney** [comment]
Great! should I close this? or open another issue?

**Comment by rlskoeser** [comment]
I just pushed a change with revised titles - could you glance over and see if it'sok ?

**Comment by clmahoney** [comment]
yes! Looks good except last graph has a typo. Needs to be "book activity" and right now it's "book activite"

**Comment by rlskoeser** [comment]
Ack, thanks - working too quickly. Corrected

**Comment by clmahoney** [comment]
Great!
