### ISSUE TITLE
As a content editor, I want to associate addresses with accounts so I can track when and where library members were in Paris and if they received mail care of another person.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#39]
Testing notes:

Designed as a mirror of associating addresses with accounts:
Addresses now have an inline where
- [ ] you can add a person using an autocomplete as a care of
- [ ] you can add other account info

**Comment by elspethgreen** [comment]
What is the status of this?  I checked just now, and it looks like we still can't search for address via person--typing in "Hemingway" didn't get me anywhere.

Mostly this will be handled on the automatic import, but it is important that when we want to manually edit things (for "care of" addresses, for example) that we don't need to look up the desired address separately in order to type it in.

**Comment by bwhicks** [comment]
@bwhicks The functionality as originally written has been implemented, but we're holding this for testing until the account-address schema tweaks mentioned in the 10/18 meeting are implemented.

**Comment by rlskoeser** [comment]
Moving this one out of logbooks admin release for now.
