### ISSUE TITLE
As an admin, I want changes made to card holders, card events, and thumbnails in the admin interface to automatically update the card search, so that content in the search and admin interface stay in sync.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#426]
# testing notes
When you edit records in the django admin, they should be automatically updated in the Solr index so that data edits are reflected in the public site.  Test by making changes in the django admin and then reloading the card search/browse page to see that your changes have been propagated.  Note that the canvas edits aren't something we would normally do manually, but it simulates getting an updated from figgy.
- cards
  - edit a bibliography card to add/remove/change an associated manifest
  - edit IIIF Canvas to change which image is the thumbnail (note: should be possible via the manifest page but that is giving me an error- try editing directly on the canvas list and changing which canvas has the thumbnail checked)
   - delete a canvas 
   - edit a cardholder's sort name
   - delete an account
   - edit an event (change one that will adjust the date range for a card)
   - delete an event (remove one that will adjust the date range for a card, e.g. the one you just changed)

Note: if you delete a person but not the account, the cards page will error. That seems like a data error to me, but if you think it may happen let me know so we can handle it.

Split out from #339

# dev notes
## handlers
- [x] thumbnails depend on manifest__thumbnail
- [x] cardholder depends on account__person
- [x] years depends on account__events

**Comment by clmahoney** [comment]
- YES, I was able to change an associated manifest on the A.W. Massey bibliography - I changed it to Lestocquoy, and when I saved and returned to the page, the manifest had updated to show the Lestocquoy manifest. Then I changed it back to the right Massey bib. 
- YES, I changed Caetani's sort name and the site now shows my edited version 
- YES, I deleted the "Basky" account, and it was gone from the site. Then I added it in again (it is only 1 reimbursement) and it was back! 
- YES, if I edit an event it changes - I edited the renewal for Account #32 "Pop" from 1920 to 1940, and the membership timeline on the site changed! 
- YES, if I delete an event it updates on the site - I deleted the Pop renewal and the membership timeline mirrors this change

- NO, I wasn't able to edit the IIIF Canvas because somehow the manifest page is gone! 
- Didn't know how to delete a canvas either without the manifest page 
![Screen Shot 2019-11-12 at 9 05 40 PM](https://user-images.githubusercontent.com/16673934/68726665-345a8b00-0590-11ea-83b9-62220f69ba2f.png)

**Comment by rlskoeser** [comment]
@clmahoney sorry about that! Just gave you back permissions to view all the IIIF database records in django admin for both qa and production.

**Comment by clmahoney** [comment]
- YES, I could edit IIIF Canvas to change which image is the thumbnail - I changed Connolly to Porcher and saw a different image in the thumbnail; then I changed it back

- YES, I could delete a canvas. I deleted s2 of Cyril Connolly - the problem is, I don't know how to add it back!
