### ISSUE TITLE
As a user browsing members pages, I want to be able to skip to the next chunk of names and be whisked to top of next page

### ISSUE THREAD

**Issue by clmahoney** [Princeton-CDH/mep-django#495]
**Describe the bug**
Right now when I'm at the bottom of the member page and I hit the "next" button at the bottom of the page, I end up at the _bottom_ of the next page. I want to be jumped to the TOP of the next page. 

**To reproduce**
1. Go to "Members"
2. Scroll down to bottom of first chunk of members (A-Culb)
3. Hit next 
4. See error - you're at the bottom of next page 

**Expected behavior**
When I hit the next button, I want to be jumped to the top of the next page. 

**Device information**
 - Device: Macbook Air 2013
 - OS and version: macOS 10 
 - Browser and version: Chrome 79,
 - Site version 0.24.1

**Comment by thatbudakguy** [comment]
note for testing - there are a couple cases where we want this to happen.

- if you click the "next" or "previous" page buttons
- if you select a new page from the page dropdown
- if you change the sort, since this will change all of the pages

it should work the same on both members and books search.

**Comment by clmahoney** [comment]
- YES this works great! I scrolled to the bottom of the member page, clicked next, and was brought up to the top of the next page! Then I went to the books page, scrolled to the bottom, hit next, and was brought to the top of the next page! Woo!
