### ISSUE TITLE
Design more states for card image viewer pagination

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#501]
- what does it look like when you are in the middle?
- what does it look like when you are at the end?
- what does it look like if there are only 1 or 2 cards?
- how does it work with a large number of card? (i.e. [Killen cards](https://shakespeareandco.princeton.edu/members/killen/cards/))
- document the logic (e.g. current card is the only fully-opaque)

**Comment by gissoo** [comment]
@jkotin @clmahoney Here are the designs for this issue: 
(zpl.io/2vk5m7n)
Please read the text on the left of each row. 
- What you see is the logic of navigating through the cards and the small card preview layout logic. 
- "Page" numbers and ranges have also been added to help the user know on which card they are as well as the total number of cards to help them anticipate the number of cards through which they would be scrolling.

**Comment by jkotin** [comment]
Thank you Gissoo!  This looks fantastic.

Questions:

1. On non-touch screens is it possible to scroll through the previews?  I can imagine users wanting to get quickly to a particular card or date, or to get a quick survey of the cards.

2. Is it possible and/or advisable to have the date ranges of the card with the large card display?  What about having the ranges under each preview image?

3. What happens if a user clicks on the image of the large card display?  Does the card image get bigger?  Can users right click and save card images as jpgs?

4. For the fewer cards scenario, will there just be fewer cards in the preview?  What if there's only one card side?

**Comment by gissoo** [comment]
@jkotin, below are the answers:
1. Yes, it is possible to scroll through the previews on non-touch screens, thanks for catching that, I've reflected it in the revised version that is accessible through the same link 

2. We could add this to the wishlist. 

3. Enlarging/deep zooming the large card display is not in scope right now.

4. Yes, there will be fewer cards in the preview. When there is only one card side it will be just like the screen on the bottom left (on the Zeplin link), with only one card preview present. (Highlighted in red, below)![Screen Shot 2020-02-13 at 11.07.56 AM.png](https://images.zenhubusercontent.com/5bf307a69d595b459ec91bb1/8ddc3955-fa5a-4205-be93-a8f326f8e2da)

**Comment by jkotin** [comment]
Thank you. Yes, we should add including dates to the wish list.  Often the date of the card is not clear from the card itself.

**Comment by gissoo** [comment]
@jkotin Please let me know if you have any other questions or comments so I can address them, if not, let's close the issue.
