### ISSUE TITLE
Edited Shakespeare and Company Address, Member Pages Stop Working

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#512]
## notes for testing
- in the admin, edit the location for Shakespeare and Company to use "and" instead of "&"
- find a member with an address and check their map; the location should show up when the name matches (after you edit it)
- if you rename that location, the pin for S&co will not show up but the page should still display and the map should render with locations for member addresses

--- 
I edited the address of Shakespeare and Company via "locations" in the database.  (I changed the "&" to an "and" and made "rue" lowercase.) Member pages stopped working. 

Here are Rebecca K.'s notes:

It looks like you edited the S&co address to fix the & to use and, but the code is looking for that address by name so it errors.

A couple of notes from my end (you can add to the issue if you create it): no need to look up the S&co address if the member doesn’t have any addresses (since there’s no map to display); and if the S&co address lookup errors, it shouldn’t keep the page from loading.

We do still need a way to look up that address; maybe we can just tweak the code to look up with the correct name. 

*

Will any revision to an address cause a similar error—albeit only for that address?

**Comment by rlskoeser** [comment]
@jkotin that address is _special_, that's the only one that will break pages like this.

**Comment by clmahoney** [comment]
- YES, after I edited the Shakespeare and Co location to read "Shakespeare and Company" instead of "Shakespeare & Company," and I changed capital "Rue" to "rue", I was able to go to a member with an address (I used Maria Jolas) and I could see her page, and her map. I was able to see her locations in relation to the newly edited "Shakespeare and Company" pin. 
- YES, after I did a joke edit, changing the name of location for S and Co to "Bob's Big Boy," I refreshed Maria Jolas's page and her location markers still appeared but the S&Co pin was gone. When I corrected the location name, the pin reappeared. So long, Bob's!
