### ISSUE TITLE
As a user viewing a member biography page, I want to see membership dates that represent actual activity so that I'm not misled by what appears to be a longer continuous membership.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#526]
## testing notes
On individual member biography page, summary membership dates should be labeled "Membership Years" and should display year ranges only, with gaps and multiple ranges reflecting actual activity. It should match the list display (now also relabeled to "Membership Years"). It should display with a "-" if the events for a member have no known year.

---
Split out from #365

**Comment by rlskoeser** [comment]
@jkotin what dates exactly do you want to display here? If we do subscriptions only, we will miss dates when we know someone was active based on borrowing events, but if we include borrowing events without a subscription it will be too many different small ranges. 

My plan was to just display the aggregated date ranges we're already using for the membership timeline chart, but for someone who with borrowing activity without a subscription it looks like this:
![Screen Shot 2020-05-06 at 9 32 13 AM](https://user-images.githubusercontent.com/691231/81183037-a4186400-8f7c-11ea-9f0a-c4ff75db5ee5.png)

**Comment by rlskoeser** [comment]
@jkotin I think the simplest thing is probably to display subscription periods, but I don't know how we label it to make it clear why that might not match the timeline.  I could see collapsing borrowing activity (or really, any date range) with small gaps (maybe less than a week), but still not sure how much that will help.  I'd prefer not to spend a lot of effort on cleaning up this information for display when we're already showing it in more detail elsewhere.

Another option would be just to display the years here ... Or only display years if there are more than some number of date ranges?

**Comment by jkotin** [comment]
@rlskoeser I would be happy only displaying years.  That's exactly the kind of info that is perfect in the member overview page: a general sense of when they used the lending library.  We could change the label to "Membership Years." Would this make more or less work for you and your team?

**Comment by rlskoeser** [comment]
@jkotin just displaying the years is less work, I've already implemented a solution for that on the members search and browse page that I can adapt.

@gissoo any concerns about this change (displaying membership years on the member biography page instead of actual dates)? Should we create a chore or add to your list so you can update the designs to match?

**Comment by gissoo** [comment]
@rlskoeser @jkotin Thanks for writing. I agree, displaying all the dates suddenly seems like such a duplicate here – Displaying years of all activities would be good (if that is what you're agreeing on above), however please **let's not** call it "membership dates" or "membership years" – we have used the term "membership" elsewhere to explicitly communicate only the subscription activities of individuals – I would suggest "Active Years" or "Activity Years" or "Years Active" 

@rlskoeser I think it's a good idea to update designs – A chore would make sense – is a chore though? Am I trying to match it exactly to format on the members search page now, though without any "..." ?

**Comment by rlskoeser** [comment]
It's called membership dates on the members list page; we should probably use the same label in both places.  I think membership is much clearer and quickly comprehensible in terms of what we want to communicate.

My sense was that we were using membership to communicate participation in the library, not strictly subscriptions — my presumption is that, for the majority of members, if we have borrowing activity there likely _was_ a subscription that we're missing.  I know @jkotin has indicated that there are times when he expects borrowing without a subscription, e.g. for friends of Beach. But wouldn't that kind of interaction with the library be "membership" of a sort?

@gissoo I don't know how much it matters to update your designs, it seems weird to revise them to match the implementation exactly. I don't think you need to read the "..." on the members page.

**Comment by gissoo** [comment]
@rlskoeser I don't think what you are saying above be "membership" of a sort. 
What I meant in my comment earlier is I don't think "membership" makes sense in either of these pages (biography and search results) – We are currently using "membership" strictly to mean "subscription" and "renewing" and "reimbursing" activities on the membership activity tab, which I think makes the most sense language-wise. 
It's very confusing and misleading for someone to view these dates on these two pages (biography and the search results) as well as the information on the membership activity page and think of them all as "membership" – According to what you are saying above it sounds like the years we are listing **can** include both the content of the "borrowing" and the "membership" tabs – which is why I'm proposing a more general term that would include "active"/"activity" ...

Regarding the designs, I think it will save us all in the long run if I update them in the near future rather than not update them at all – agree that it may not be urgent right now

**Comment by jkotin** [comment]
Maybe the membership timeline makes the "membership dates" unnecessary.  I like it nonetheless -- it provides a very fast way to understand when a member used the library.  Users will want to know that Jane Smith used the library in 1933 and not 1922, e.g.

"Active Member" would be OK phrase.  "Membership Years" is likely the clearest.

**Comment by gissoo** [comment]
@jkotin thanks for writing – I was proposing "Active Years" or "Activity Years" or "Years Active" – I don't think "Active Member" makes sense for displaying the years.

**Comment by jkotin** [comment]
"Years Active" is great with me!

**Comment by jkotin** [comment]
On second thought, will "years active" make sense in context?  I worry users will think "active" at what?  Especially when the dates are so close to the birth-death years.  I like keeping "membership" so everything is clear.  As @rlskoeser notes, we use the term in a non-technical way to indicate when a person was an active part of the lending library community.  A lot of members didn't buy memberships.

**Comment by gissoo** [comment]
@jkotin As I have noted above I'm worried that for individuals who have not been working on this project it gets confusing – Is this information exactly the same as the information in the "Membership Activity" tab? That tab includes information about "Subscription", "Renewing", and "Reimbursement" activities and nothing else, hence it's called "membership" – I need to point this out since we have been working on this project for such a long time that we may miss how it might be read from the outside.

**Comment by jkotin** [comment]
I hear you.  I think users will understand "membership activity" as encompassing all activities related to membership, i.e. renewals, reimbursements, etc. I think users will understand "membership years" as encompassing all the years they borrowed books from the lending library.

Maybe this isn't perfect, but I'm still convinced it's the best option. I can also see the argument for not including this information due to the membership timeline.

Two questions: do we determine the timeline with different data than we would determine the membership years?  Or are these simply two different ways of presenting the same information?  I've been understanding it as the latter.

**Comment by rlskoeser** [comment]
@jkotin I agree with you — I think "years active" is too vague.

Timeline and membership years are based on the same data.  Same information, presented two different ways, with differing granularity. (We _could_ filter them differently, but I wouldn't advise it.)

**Comment by jkotin** [comment]
All good!  (I'm happy/relived re: timelines and membership years!)  Let's go with "Membership Years" for now. 

I can imagine a future time in which we place the information in membership years closer to the timeline, but I'm very happy with this layout now.

**Comment by gissoo** [comment]
@jkotin I think it's important for it to be on the search results because there is a filter for it and it would be nice to see the years there if someone is using the filter – it does add more context 

@jkotin @rlskoeser I'm not convinced yet! But since you're both on the same page there isn't much I can do right now other than letting it go :D – happy to wait and see what users will think in the future.

**Comment by clmahoney** [comment]
- YES, if I go to a member detail page I see the active "Membership Years" in a list form. Ex: Killen: 
![Screen Shot 2020-05-06 at 10 53 59 PM](https://user-images.githubusercontent.com/16673934/81249433-939fd200-8fec-11ea-9d65-849a1363ccac.png). Ex: Hemingway: 
![Screen Shot 2020-05-06 at 10 55 10 PM](https://user-images.githubusercontent.com/16673934/81249503-c4800700-8fec-11ea-9c25-e7bb74332b94.png)
