### ISSUE TITLE
Card size in desktop card browse should be larger.

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#542]
As it stands (0.26), users can read the cards in the card browse when the handwriting is clear, but not when the handwriting is unclear, which is often.  When the handwriting is unclear, users will want (and need) to look at the cards more closely.  Currently that's only possible if users download the cards or magnify their screens, both awkward solutions.

Card should be 10%–20% larger or there should be a way to expand them.  For example, click on an image in this photo essay: https://www.moma.org/magazine/articles/245.  I think the MOMA solution is better than a zoom function or a link to the finding aid.

This request may sound superficial, but it really challenging to try to identify books on the cards. The size of the cards limits accessibility.

**Comment by rlskoeser** [comment]
@jkotin thanks for documenting this. Could you add a few links to example cards that are difficult to read?

**Comment by jkotin** [comment]
Some cards I was looking at yesterday -- fairly random:

https://shakespeareandco.princeton.edu/members/fournier-jeanne/cards/850d416e-87c0-4b3f-95f7-522f3b86f3a3/

https://shakespeareandco.princeton.edu/members/fournier-jeanne/cards/ca873c36-db50-4c95-9bf4-efe1e0a9ec23/

https://shakespeareandco.princeton.edu/members/shelley-dorothy/cards/f7380032-e245-494c-99f8-3047e146b117/

https://shakespeareandco.princeton.edu/members/schirmer/cards/f11ab628-bbb5-4d9f-af20-a612b63b23dc/

These are just regular cards. I could find some tricky cards with lots of cross-outs or strange handwriting.  (To locate those, search for HANDWRITING in the works database.)

**Comment by rlskoeser** [comment]
Thanks for providing these examples, that makes the problem clearer.

**Comment by gissoo** [comment]
@rlskoeser [here are the solutions I'm proposing. ](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ec2ea34026c9a30e1b0f40c)

v1. Click on the image to zoom, click out of the image to zoom out 
v2. Zoom button on the side (top) – on lick magnifies parts of the image when hovering over the image with it
v3. Another version of v2 – not a fan, just testing for UX purposes as it might be more desired by users 
v4. Make the image larger with no zoom options 
v5. Zoom button on the side (top) – on click enlarges the image, almost full screen (helpful to still see the page header with the nav and the title) with + - buttons on the side with an x button to close the zoomed window
v6. same as v5, except the  < > buttons are available in the full screen mode to make navigation much more convenient. 

Please let me know what you think.

**Comment by rlskoeser** [comment]
I like v5 and v6 best (prefer v6 if we can make it work, which I think we should be able to). I might be partly biased towards those because I actually know how to implement them (no idea how the magnifying glass would work!); but I do think it will be a better solution than the other options in terms of functionality and interaction.

Clarification question, just to make sure I'm understanding what you intend: when the zoomed version of the image  is active, does it fill the bottom of the page? You have to close it to get back to the view where you can see the table of events?

**Comment by gissoo** [comment]
> I like v5 and v6 best (prefer v6 if we can make it work, which I think we should be able to). I might be partly biased towards those because I actually know how to implement them (no idea how the magnifying glass would work!); but I do think it will be a better solution than the other options in terms of functionality and interaction.
> 

@rlskoeser When you say "but I do think it will be a better solution than the other options in terms of functionality and interaction" – do you mean the magnifying glass one? 

What about v1? I'm not fond of v5 and v6 in general, it is what is used most often and I'm not sure they are necessary – too dramatic and overwhelming at times. But I understand we are limited in time and if you know how to implement that best it makes sense to me. 
 
> Clarification question, just to make sure I'm understanding what you intend: when the zoomed version of the image is active, does it fill the bottom of the page? You have to close it to get back to the view where you can see the table of events?
>

It does. However, it would improve the interaction if it doesn't! If we decide to go with this, can we do v6 (so navigating the cards would be better) and show the activities table? I can revise designs.

**Comment by rlskoeser** [comment]
@gissoo sorry I was unclear! I think the deep zoom provides better functionality since there is more control and allows for more zoom levels. 

Looking again, I see that V1 would probably be the simplest to build.  It's full-screen right? Click to get the image full-screen, click again to go back to the normal view.  Do you think it's big enough for everyone to read on all devices? Might still be small on mobile.

**Comment by rlskoeser** [comment]
I'm not sure how the activities table would fit vertically, but I think it would at least be possible on v5/v6; not sure how it would work with v1.

**Comment by jkotin** [comment]
Just interrupting this -- disregard if unhelpful! -- I don't think the card size is an issue on mobile or tablet. It's easy for users to zoom in / enlarge the page.  I also don't think we need full-on zoom feature on desktop. If users want to look incredibly close they can save a jpg of the card or go to the finding aid. What's important to me is that users can easily make the cards readable on desktop. Clicking the card and getting a large card would be great!  I would prefer if the magnifying glass icon were on the upper right as in option 2.

**Comment by rlskoeser** [comment]
Thanks @jkotin — to be clear, you prefer the functionality in V1 but with the magnifying glass positioned as in V2? 

@gissoo It occurs to me know that we shouldn't have the minus magnifying glass over the enlarged image either, it will obscure content in many cases.  Do we even need these? Can we just make the image clickable?

@jkotin the mobile/tablet zoom in enlarges the page but doesn't increase the image resolution like deep zoom does (which actually loads higher resolution tiles on demand). Even downloading the card image still won't give the same resolution as we can provide with deep zoom.

**Comment by gissoo** [comment]
> @gissoo sorry I was unclear! I think the deep zoom provides better functionality since there is more control and allows for more zoom levels.
> 
> Looking again, I see that V1 would probably be the simplest to build. It's full-screen right? Click to get the image full-screen, click again to go back to the normal view. Do you think it's big enough for everyone to read on all devices? Might still be small on mobile.
>

@rlskoeser  I think it's big enough – and it's so quick and easy to navigate in comparison with some of the other options. Seeing the cards or navigating them easily doesn't have to exist in v1, v1 is naturally a quick interaction and doesn't require as much effort as v5 and v6, for instance.

@jkotin Thanks for writing. The reason I would agree with v1 is that there is no magnifying glass on top right – we can add a hint text or something to say something like "click on image to view full width" – but the whole purpose is to not have to click on anything outside of the image to interact with it, that's where all the effort is saved, especially if it will be done repetitively by the user for each card. 

@rlskoeser @jkotin v6 will be a better option if you think you want users to be looking at a larger version of the card on the site at all times.

**Comment by jkotin** [comment]
Yes, I like v1. I agree with @rlskoeser that the magnifying class is probably unnecessary.  I think users are used to clicking on an image and getting a bigger version.  (My example of what I envisioned was the MOMA site: https://www.moma.org/magazine/articles/245.) Deep zoom isn't a priority for me.  A very small percentage of users might want super detailed images, but most will just want to read the cards.  I can create a FAQ along the lines of "How can I get higher-quality versions of the lending library cards?" Then I can provide a link to the finding aid, which allows the public to download TIFFs.

**Comment by gissoo** [comment]
@rlskoeser having the minus magnifying glass plays a role in making the interaction light and seamless – rather than an x button at the top of the window to close the large image window – it creates an ease on the user on how they can go back to the previous view of the page, I'm not sure how valuable this is without the easy in and out of the + and - magnifying glass.

**Comment by rlskoeser** [comment]
Ok, I'm happy to proceed with V1 approach. 

@gissoo maybe the magnifying glass icon could show on hover?

It occurred to me we can implement it in a way that pulls in a higher-resolution version of the image appropriate to the device — @gissoo would you recommend sizes when you revise?

**Comment by gissoo** [comment]
@jkotin thanks for writing and for the example. what MoMA is doing makes sense for an article page with single images along the page, however for our purpose on the card image viewer page I don't recommend it at all because it makes navigating through the cards on a page a pain. 

@rlskoeser Thanks for writing. What do you mean when you say "maybe the magnifying glass icon could show on hover?" – It is currently that way by default, do you mean that for when the image is enlarged? I agree with that (I think I intended that, but was trying to show "actions" in the mock-ups, sorry for the lack of clarity)

@rlskoeser Sure, I can recommend sizes when revising.

**Comment by rlskoeser** [comment]
@gissoo sorry — are you saying from that the +/- magnifying glass icons in your mockups will only show on hover? I didn't understand that. If that's the case, then I prefer the icon in the middle of image instead of above it.

Is there any good way to show the magnifying glass for touch devices that don't have a hover event?

**Comment by gissoo** [comment]
> @gissoo sorry — are you saying from that the +/- magnifying glass icons in your mockups will only show on hover? I didn't understand that. If that's the case, then I prefer the icon in the middle of image (V1) instead of above it (V2).
> 

- Yes, they would show on hover. What I mean is the cursor becomes the magnifying glass – that was my original intention with v1. The magnifying glass does not have a designated spot. Is this feasible? I don't think having it in the middle makes sense. 

> Is there any good way to show the magnifying glass for touch devices that don't have a hover event?

- Is it feasible to have a text above the image "select image to zoom in/out"?

**Comment by rlskoeser** [comment]
@gissoo oh, we just set the cursor to `zoom-in`? That's great.

We can add the text to display on mobile/tablet if you think it's necessary/helpful.

**Comment by gissoo** [comment]
@rlskoeser Yes!! Thank you!!! I'm sorry that I thought I was so specific and yet I was still so vague :\ 
It would be great to add the text for displaying on mobile/tablet! I think it will be helpful.
I'll work on the enlarged image sizes now that it seems we have reached some agreements here.

**Comment by gissoo** [comment]
@rlskoeser [This is how I'm thinking about the card sizes](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ecd93618bc3ca4a1dd5c0f7)

Does it make sense to you?

**Comment by rlskoeser** [comment]
@gissoo yes, I think I should be able to figure out what IIIF sizes I need from that.

**Comment by gissoo** [comment]
@jkotin @rlskoeser Just want to make sure we agree on this and we can close it. [Here is what I'm proposing](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ecedfe7effff92823006c4a)

Please take a look at the hint text and its language, let me know what you think about this. (can't be grey because there is not enough color contrast with the background on this page)

And, this is what I showed to @rlskoeser which she is okay with: [This is how I'm thinking about the card sizes when enlarged](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ecd93618bc3ca4a1dd5c0f7)

**Comment by jkotin** [comment]
Thank you @gissoo. It's a little difficult for me to imagine how it works in practice. (My brain.) But I think this looks great.  Questions and notes:

1. How does the magnifying glass look on a very "busy" card? The Benjamin card has a lot of white space. Most cards are covered in writing. The magnifying glass might be obscured.

2. Could the grey of the background be the same color independent of zoom?  I.e. I think the color should be the same when the card is large or regular. (The zoom grey looks darker to me.)

3. Do we need a zoom feature on tablet and mobile? Can't users "zoom" in with their finger tips?

4. For help text, how about "tap image to zoom"?

5. Have you tested the size for cards that are especially difficult to read. There's a list above.

**Comment by gissoo** [comment]
> Thank you @gissoo. It's a little difficult for me to imagine how it works in practice. (My brain.) But I think this looks great. Questions and notes:
> 
>     1. How does the magnifying glass look on a very "busy" card? The Benjamin card has a lot of white space. Most cards are covered in writing. The magnifying glass might be obscured.
> 

- I tested with them too, it will still be visible on these images. This is true especially because there is a sudden change from the "hand icon" cursor to the "magnifying glass" cursor. 

>     2. Could the grey of the background be the same color independent of zoom?  I.e. I think the color should be the same when the card is large or regular. (The zoom grey looks darker to me.)
> 

- Thanks for pointing out! Yes, I have revised it (that grey was not intentional here)

>     3. Do we need a zoom feature on tablet and mobile? Can't users "zoom" in with their finger tips?
> 

- I defer to @rlskoeser on this. I'm okay either way. 

>     4. For help text, how about "tap image to zoom"?
> 

- The language I picked was me being worried that some users won't know they can tap on the enlarged image on tablet and mobile again to "zoom out" because there is no way to see a magnifying glass cursor. This text would go away if we decide to not do this feature for tablet and mobile. (Since "Zoom" is most often incorrectly associated with "zoom in" rather "zoom out") 

>     5. Have you tested the size for cards that are especially difficult to read. There's a list above.

- Yes! I did test it with them. I had to use another tool to simulate it. The idea is that the images depending on the orientation of the device and the image will either take the full height of the screen or the full width, they will be very visible! @rlskoeser Just tagging you to make sure you see my response to this particular question in case.

**Comment by jkotin** [comment]
@gissoo Great!  I'm happy to sign off. I don't think we need the zoom for tablet/mobile, but I defer to @rlskoeser too on this. If we do need language for the zoom, "tap image to zoom in/out" is fine with me.

**Comment by rlskoeser** [comment]
It's easier for us to implement features like this the same way across devices, but I do think it's valuable for tablet/mobile because we can provide a higher resolution version of the image, rather than just enlarging the existing one.

**Comment by gissoo** [comment]
@jkotin Thanks for writing. 

@rlskoeser Thanks for writing! I was suspecting that was the case! It will be helpful then, I vote for applying it to tablet and mobile. 

Great, then just to make sure, we are agreeing that this feature will be on all devices, where once a card image is enlarged it's either full height or full width depending on device and image orientation (following the design guidelines I had previously shared [here](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ecd93618bc3ca4a1dd5c0f7))   and the language for the hint text would be "tap image to zoom in/out". 

[Also, shared this before, here is how the interaction would look like for this specific card example on all devices](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ecedfe7effff92823006c4a)

@jkotin Please close if you don't have any concerns.
