### ISSUE TITLE
Compensate for spacing between initials in book searches

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#547]
Would be great if both "T.S. Eliot" and "T. S. Eliot" would lead to T. S. Eliot in book searches.  Ditto for other authors and subjects with initials—e.g. G. K. Chesterton, D. H. Lawrence, etc.  

## testing notes
- test both member and book search
- should get same results with and without a space in initials; recommend testing with _just_ "t.s."/"t. s." or "d.h" (omit other terms and last names) to compare directly
- do a few other test searches to make sure this change hasn't broken anything else

**Comment by rlskoeser** [comment]
@jkotin does this apply to member search as well, or only book search?

**Comment by jkotin** [comment]
@rlskoeser it's much more important for author searches, but would be great for members too.

**Comment by clmahoney** [comment]
Members: 
- YES, if I omit spaces in names (e.g. T.S. instead of T. S.) I see all results, as if I had written T. S. like it's spaced on the site 
but 
- NO, if I type in "T.S " which is T dot s space, I get NO RESULTS. I get results when I add the period after s. 

Same thing in books: 
- YES, if I omit spaces in names (e.g. D.H. instead of D. H.) I see all results, as if I had written D. H. like it's spaced on the site 
- NO, if I type in "D.h " which is D dot h space, I get only 1 result, not the 291 I get when I type in "D.h." or "D. H." 
- also NO, if I type in "dh" I don't get any results (not sure that was what I should be testing though) 

General: 
- YES, I poked around searching for other things and couldn't find anything else weird

**Comment by rlskoeser** [comment]
@clmahoney my understanding based on Josh's request was that we only cared about T.S. / T. S. and not T.S or TS, so I think your testing results match what we want.

@jkotin can you confirm I've understood correctly?

**Comment by jkotin** [comment]
I'm not worried at all about "T.S" -- but is "TS" something that we should anticipate?  Regardless: "T.S." and "T. S." are by far the MOST important -- I'm happy if the search responds to both.

**Comment by rlskoeser** [comment]
It's entirely possible people will try "TS" (it's amazing what people do that we can't anticipate), but I don't think splitting that automatically is a good idea because it could easily cause problems for legitimated two letter words.

**Comment by rlskoeser** [comment]
@jkotin based on your answer, it sounds to me like Cate's testing confirms this is working the way we want. Do you want to test/review/close ?
