### ISSUE TITLE
circulation activity table mobile design: edge cases

### ISSUE THREAD

**Issue by thatbudakguy** [Princeton-CDH/mep-django#579]
the mobile design for the circulation activity table is difficult to achieve because of some of the constraints on how we can use the elements in it (see discussion below). these constraints are unfortunate byproducts of the fact that the markup for the page corresponds to a table (not anything implied by the design, just a fact of how browsers work). it would be useful to know how important these choices are to the overall look/message of the page:

- combining the two dates into one line with a dash separating them
- having the edition info floating on the right side

linked discussion below touches on why the current design is tough to implement.

>I tried the same technique used on borrowing activities, which absolute-positions content on the right side, but that doesn't work for long edition titles:
><img width="366" alt="Screen Shot 2020-04-28 at 12 02 25 PM" src="https://user-images.githubusercontent.com/4924494/80510103-449cd180-8948-11ea-9acc-802a58b4bbf2.png">
>the main issue is that the layout implies columns or other structure that wraps parts of the row, but `<div>` aren't allowed inside `<tr>`, so we can't use them to break up the `<td>`s into groups that can then be sized accordingly.
>it gets even more complicated because we have to give the appearance of collapsing start and end dates into one dash-separated field, but that field usually needs to take a whole line even though either one of its "parts" could be empty.
>i think we may need to compromise on some of these designs - the need to represent them semantically as a table make it quite difficult to achieve other complex, non-tabular representations.

_Originally posted by @thatbudakguy in https://github.com/Princeton-CDH/mep-django/pull/572#issuecomment-620703693_

**Comment by rlskoeser** [comment]
@gissoo Here's my stab at implementing this layout, which is currently on the test site:
![Screen Shot 2020-04-30 at 10 09 54 AM](https://user-images.githubusercontent.com/691231/80720364-cc124e00-8aca-11ea-9c14-320a6ebf1d4a.png)

I had to give the right-side edition information even less space to avoid potential overlaps with the dates, and I'm truncating the title for space (because otherwise they overlap, as you see in Nick's screenshot). We ought to add some indication that the title is truncated, and I started trying a CSS solution for that but it didn't adapt exactly to our needs.

There's another question around logic for date ranges with a missing date, I don't know if it makes sense to include in this issue or if it's a separate issue — Nick suggested we could include a dash in the table for date ranges, which would make it much easier to show the dash for events that are ranges and hide it for single-day events like purchases and reimbursements.

**Comment by gissoo** [comment]
> @gissoo Here's my stab at implementing this layout, which is currently on the test site:
> ![Screen Shot 2020-04-30 at 10 09 54 AM](https://user-images.githubusercontent.com/691231/80720364-cc124e00-8aca-11ea-9c14-320a6ebf1d4a.png)
> 
> I had to give the right-side edition information even less space to avoid potential overlaps with the dates, and I'm truncating the title for space (because otherwise they overlap, as you see in Nick's screenshot). We ought to add some indication that the title is truncated, and I started trying a CSS solution for that but it didn't adapt exactly to our needs.
> 

- @rlskoeser @thatbudakguy Thanks for writing. I was trying to look at the books URL to get to a circulation table on the test site and can't access it, my vpn is on. 
But I understand the problem here, thanks for providing all the explanations. I think this truncation works, can we use "..." as an indication?

> There's another question around logic for date ranges with a missing date, I don't know if it makes sense to include in this issue or if it's a separate issue — Nick suggested we could include a dash in the table for date ranges, which would make it much easier to show the dash for events that are ranges and hide it for single-day events like purchases and reimbursements.
>

Nick also has written this, above: 

>"it gets even more complicated because we have to give the appearance of collapsing start and end dates into one dash-separated field, but that field usually needs to take a whole line even though either one of its "parts" could be empty."
>

- Are we still specifically talking about adding the dash on mobile? (I've already included dashes in place of missing dates on desktop and tablet, the design would be the same for mobile) Is this what you're talking about? I'm not sure I'm following. 

I'm guessing you are talking about an additional field for dash to be put between the two "start date" and "end date" columns that would appear on desktop and tablet? Because I'm not sure that's a good idea. Unless if we could hide that column on desktop and tablet?

But if you're just talking about mobile it would be like this:

Pierre Vogein
Borrow
– Nov. 27, 1925

Pierre Vogein
Borrow
Oct. 31, 1925 –

?

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy I know RSK and I briefly talked about this issue, however since I didn't get explicit responses from you on here about my comment, I took a stab with the designs here based on my proposal in my previous comment, please let me know what you think. 

[Designs are here.](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5eb32cc172876a4ea81c94bc)

**Comment by rlskoeser** [comment]
@gissoo thanks for working on these. I think putting the dates on a separate line will simplify the layout substantially, but I'd like to hear what @thatbudakguy thinks.

Could you add a few more variations to the design so we can see how they look and all be clear on the specifics?
- at least one single-day event like a purchase 
- at least one event with no issue/volume information

Have the desktop and tablet designs changed in any way, or do you just include them for completeness, so we can see the same events in all views?

**Comment by thatbudakguy** [comment]
agree that putting them on separate lines would make it substantially simpler. i think the designs imply this, but we would need to set a hard limit (e.g. 50%) on the size of either column in order for the layout to work. I believe it can then be accomplished with floats.

**Comment by gissoo** [comment]
@rlskoeser Thanks for writing. Sure I'll revise to include the variations you have mentioned above, that's helpful thanks for listing them! 

@rlskoeser The design on desktop and tablet have not changed. However, I included them especially because now I have made sure the information presented is consistent throughout all devices: I have added a third row/person to complete the variations with dates to all the devices and I have also fixed the end dates everywhere so they when they exist they are all complete dates. I just include all devices for sake of consistency of content and as well as completeness. 

@thatbudakguy As I'm revising I will make sure the limit I have set is consistent and explicit, thanks for pointing out!

**Comment by gissoo** [comment]
@rlskoeser @thatbudakguy [Here are the revisions](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5eb32cc172876a4ea81c94bc), you can see the variations you were asking for in the mobile design for the "Psychology of Sex" – also included more variations with the volume/issue content. 

@thatbudakguy I have made a comment about the hard limit for the size of the columns on mobile in % – let me know what you think and if you need anything else.

**Comment by rlskoeser** [comment]
@gissoo thanks for your work on this and for adding more variations.  

For the purchase on mobile, shouldn't we only display one date? It seems confusing to display it as a range.

@gissoo Will this look unbalanced on mobile if there is _no_ issue/volume information? I think that's likely to be the case for the majority of borrowing events. For an example, see [circulation for Portrait of the Artist on the test site](https://test-shakespeareandco.cdh.princeton.edu/books/joyce-portrait-artist-young/circulation/).  Could you show one example of the mobile with no issue/volumes (could be a copy of one of your current versions).

**Comment by rlskoeser** [comment]
@gissoo actual numbers to help you: we have 22,285 events in the database associated with a work (e.g. borrows, purchases, etc) but currently only 439 with an edition (issue/volume) specified. That number will go up some as the team keeps working on it, but it's a very small proportion (just under 2%).

**Comment by gissoo** [comment]
> @gissoo thanks for your work on this and for adding more variations.
> 
> For the purchase on mobile, shouldn't we only display one date? It seems confusing to display it as a range.
> 

I did this on purpose – I think it can be helpful and more specific and less likely to be overlooked by users – Especially since they are both shown on other devices. Not sure yet, happy to think more and come back to it. 

> @gissoo Will this look unbalanced on mobile if there is _no_ issue/volume information? I think that's likely to be the case for the majority of borrowing events. For an example, see [circulation for Portrait of the Artist on the test site](https://test-shakespeareandco.cdh.princeton.edu/books/joyce-portrait-artist-young/circulation/). Could you show one example of the mobile with no issue/volumes (could be a copy of one of your current versions).
>

@rlskoeser I already have a variation with no vol/issue example in the designs for one row. 
Do you mean showing an entire page with no volume/issue information? – I think it will look fine and not unbalanced! Happy to revise and think more about this. I'll update you.

**Comment by rlskoeser** [comment]
@gissoo yes, I think it would be useful to see an entire page with no volume/issue information. If you think it looks fine, that's great! I don't really want to revise it at this point, I just wanted to be sure, since that's what the majority of pages will look like.

I think displaying purchases as a range (when we know it is a single date) seems more likely to be overlooked when scanning the page, and it would stand out more without, especially since we'll be fixing the others to always display the dash even if only one date is known. I don't think parity with the other screens matters — we only include end date on purchases in the table for sorting purposes.

How did we handle single date events on the other mobile activity pages (borrows, reimbursements)? I thought we only showed one date.

**Comment by gissoo** [comment]
> @gissoo yes, I think it would be useful to see an entire page with no volume/issue information. If you think it looks fine, that's great! I don't really want to revise it at this point, I just wanted to be sure, since that's what the majority of pages will look like.
> 

I revised the designs and included a screen with no vol/issue info. It looks okay to me, but here is one thought/proposal: Is there a way to put the end date on the same line as the start date for when there is no vol/issue info? – That might help it look more balanced in this case.

> I think displaying purchases as a range (when we know it is a single date) seems more likely to be overlooked when scanning the page, and it would stand out more without, especially since we'll be fixing the others to always display the dash even if only one date is known. I don't think parity with the other screens matters — we only include end date on purchases in the table for sorting purposes.
> 
> How did we handle single date events on the other mobile activity pages (borrows, reimbursements)? I thought we only showed one date.
> 

Thanks! I agree, I have revised it. It is also a single date for the other cases.

[here are the designs](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5eb32cc172876a4ea81c94bc)

**Comment by rlskoeser** [comment]
@gissoo thanks for revising and adding an example with no issue/volume information. It looks a little unbalanced to me, but I'm glad to hear you think it's ok.

I think putting the end date on the same line as the start date when there's no edition information would be too complicated — there are just too many different cases to handle (issue/no issue, missing start date, missing end date, missing both dates, single-date events). @thatbudakguy what to you think??

I think if we want the dates on a single line we should _always_ do that, and need to de-prioritize the issue/volume information - e.g., list it afterwards and slightly de-emphasize it as we do elsewhere (e.g. gray font, smaller type — although not sure we can/should go smaller here). I don't think we need to make that change, but I don't think we should have two different layouts.

**Comment by gissoo** [comment]
@rlskoeser That makes sense! Thanks for writing. (I also suspected that strongly but had to see what you think) – I think we shouldn't sacrifice the readability of the vol/issue info for how balanced/unbalanced the page looks. I think it's worth giving the second column its space. I really didn't like how tight it looked (the vol/issue column).

**Comment by thatbudakguy** [comment]
@gissoo when you say "I really didn't like how tight it looked", how tight are you thinking? As I mentioned earlier, we will need to choose a percentage that the volume/issue column gets to take up, regardless of the size of the text in it. i think if we always put the dates on separate lines, we can afford to give the volume/issue column 50% or more of the record, but if we don't do that things could get pretty cramped. if this works for you, great!

agree with @rlskoeser that changing the layout based on if volume/issue info is available is probably too complicated.

fwiw I'm fine with listing the volume/issue info at the bottom in the way @rlskoeser mentioned, but I understand why it might not be the best approach (though it's certainly the simplest).

**Comment by gissoo** [comment]
@thatbudakguy Thanks for writing.
I had made decisions and shared designs last week and asked you what you thought, [in this comment above](https://github.com/Princeton-CDH/mep-django/issues/579#issuecomment-625486913). Please take a look and let me know. This is the best option UX-wise.

**Comment by thatbudakguy** [comment]
@gissoo I'm happy with the version you shared, which looks like it gives the volume/issue info portion 50% of the space - was asking because I didn't know which thing you were referring to when you said it looked too tight.

**Comment by rlskoeser** [comment]
@thatbudakguy I assumed it was my implementation that was too tight, where I squeezed the issue/volume column to make sure it didn't overlap with the dates.

**Comment by gissoo** [comment]
@thatbudakguy I was referring to the vol/issue information – and then RSK mentioned that what I'm proposing might make the layout unbalanced for when there is no vol/issue info, so I was saying I still prefer what I'm proposing because in this version the vol/issue info is not too tight like how it is now on the site. (And it's really the dates being on two lines that make it look unbalanced more than the percentages that I have chosen) but still I prefer this!

**Comment by gissoo** [comment]
@jkotin Please take a look at [the designs here](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5eb32cc172876a4ea81c94bc) and let me know what you think. 

You can focus mainly on the **mobile** screens. The design on mobile is revised so that:
- the start date and the end date are on two separate lines rather than all on one (due to complexities with developing the table layout on mobile as well as problems with the column on the left and the column on the right overlapping – for when there is vol/issue information)

- The size of the two columns have been slightly adjusted so that the vol/issue information won't have to be so tight, they will be more readable. 

- Events such as a "purchase" will have a single date displayed for them on mobile.

**Comment by jkotin** [comment]
@gissoo This looks great to me.

My one question concerns missing dates. In the Jean-Dominique Rey case, I assume that we don't have a start date, only a return date, hence the " – Mar. 17, 1967." Would it make sense to have an "unknown" or "?" as the start date as opposed to nothing?  I worry that users will think " – Mar. 17, 1967" is a mistake.

I'm happy to defer to you on this issue.

**Comment by gissoo** [comment]
@jkotin I really think it is clear enough as is, however I understand that a "?" might make it more explicitly clear. @rlskoeser What do you think? Is a "?" possible?

**Comment by rlskoeser** [comment]
@jkotin @gissoo "?" is possible if we also display that in the table layout — would that be ok?

**Comment by jkotin** [comment]
I vote a weak YES. Best to include the question mark.  The vote is weak because I would be happy to defer if either of you had a strong NO.

**Comment by rlskoeser** [comment]
FWIW, implementation would actually be a lot easier to use the question mark and not have to selectively hide missing dates on mobile. I don't have a strong inclination in terms of which one is more comprehensible, although I do like that the question mark makes the missing data more explicit.

@gissoo does this change your design any? Is it still ok to have start and end dates on separate lines if one of them is just a question mark?

**Comment by gissoo** [comment]
@jkotin @rlskoeser thanks for writing!! Great! I definitely agree then! Yes it will be nice that it might be more explicitly clear this way. Thanks. 

@rlskoeser No, it shouldn't change anything about the design. I'll just update the designs though.
Are we thinking the "?" is appearing on the circulation page on the all devices when a date is missing? Or just on mobile?

**Comment by rlskoeser** [comment]
@gissoo the question mark _needs_ to be on all devices (that's what my question was about — can we display it in the table layout also).

**Comment by gissoo** [comment]
@rlskoeser Sorry! I probably shouldn't be doing multiple things when reading these comments. 
It makes sense to me that it will be on all devices. 

So just testing this as you wrote: "Is it still ok to have start and end dates on separate lines if one of them is just a question mark?" [in this design](https://app.zeplin.io/project/5c48e7313d2b13bf7fc9fe14/screen/5ebb0768efce0a5ad7b5d351) @rlskoeser @jkotin Does this look okay to you? Please look at the second and third rows. They looked a bit weird to me, especially the one with the missing start date where "? –" are next to each other.

**Comment by rlskoeser** [comment]
This looks ok to me.

**Comment by jkotin** [comment]
I agree that the second and third rows look strange.  The question mark, when split, might cause more confusion than it resolves.  I'm OK with it if we think that the question mark makes things clearer in desktop.  Otherwise, let's go back to the original plan.

**Comment by gissoo** [comment]
@rlskoeser @jkotin Thanks for writing.

Rebecca, you mentioned "implementation would actually be a lot easier to use the question mark and not have to selectively hide missing dates on mobile." – is this also true about "unknown"? I think "unknown" as Josh had mentioned in his earlier comment might be more clear, thought it's worth to discuss this.

**Comment by jkotin** [comment]
I prefer "unknown" if there's space for it.

**Comment by rlskoeser** [comment]
@gissoo it's easiest if we don't have to change things too much between different views. I'm ok with "unknown" as long as we can use it on all screens.

**Comment by rlskoeser** [comment]
@gissoo however.... how many other pages does this impact? If we have to do this on multiple pages it is a bigger change.

**Comment by gissoo** [comment]
@jkotin there is space for it.

@rlskoeser I was thinking on all devices. 

Okay, here is where I stand:
- I was thinking it will impact circulation pages (desktop, tablet, mobile) 

- And then I thought about member borrowing activities (desktop, tablet, mobile) + membership activities (desktop, tablet, mobile) – unless you have a reason to think that it wouldn't be necessary to apply the "unknown" rule to these pages 

Therefore, 
- If you think it will be needed on all of these pages, and that's too many places, I vote for keeping things as they currently are (nothing displayed for a missing date)

- If you think it will be needed on all of these pages, and that's **not** too many places, I vote for displaying "unknown"

- If you think it's just a for the circulation pages, and that's not many pages, I vote for displaying "unknown"


I hope I have covered all possibilities :D @rlskoeser @jkotin

**Comment by jkotin** [comment]
I'm happy with any of these three options.  If we're still unsure, it would be helpful to see a mock-up of a desktop page with a lot of "unknowns."  It matters whether "unknown" would simplify other aspects of the project.

**Comment by gissoo** [comment]
@rlskoeser @jkotin I forgot about the card image viewer page!

**Comment by rlskoeser** [comment]
@gissoo thanks for listing all of those — it seems like we should treat unknown dates consistently across the site, and that feels like a lot of changes to me. I vote for keeping things as they currently are, nothing displayed for a missing date.

**Comment by jkotin** [comment]
That's fine with me, and probably prudent.  Thank you all for thinking/seeing this through with me.

**Comment by gissoo** [comment]
@rlskoeser I agree! I'm also still having mixed feelings about a desktop/tablet page with so many "unknowns".

**Comment by gissoo** [comment]
@jkotin @rlskoeser I think we reached an agreement on this issue to keep it as is.
@jkotin Please close the issue if you don't have any concerns.
