### ISSUE TITLE
Build people module

### ISSUE THREAD

**Issue by bwhicks** [Princeton-CDH/mep-django#6]
Build and write tests for the people database module.

- [x] Build all models with basic (non-ForeignKey M2M fields)
- [x] Verify `__str__` and `__repr__` methods for each, as well as any field validation
- [x] Create M2M and any through tables if applicable (may need to work in tandem on other modules)
- [x] Test M2M relationships and any helper functions added to classes

**Comment by bwhicks** [comment]
![image](https://user-images.githubusercontent.com/17815297/27440980-3271bb62-573a-11e7-881e-43efba2e19dc.png)

Add a snip of the module for reference to the thread.

**Comment by bwhicks** [comment]
A few questions prompted by digging in (directed at @jabauer and @rlskoeser):

1) The table names are plural. Presumably I should do these in Django in the singular (i.e. Person), with verbose for pluralization.
2) `viaf_id` is an integer field, but in previous projects we did them as URIs. This is probably obsoleted by the discussion of needing multiple urls for people anyway.
3) I assume `title` should be unrestricted and not a choice field.
4) For `birth_year` and `death_year` I used the `AliasIntegerField` class and the `DateRange` mixin. This gets us validation with pre-existing code. It does mean that the table in the database will list `start_year` and `end_year`, but Django will know it as `birth_year` and `death_year`. Thoughts?

I've tried to flag code in question with `# QUESTION:` tags in `mep/people/models.py`

**Comment by rlskoeser** [comment]
@bwhicks thanks for flagging these.

> 1. The table names are plural. Presumably I should do these in Django in the singular (i.e. Person), with verbose for pluralization.

Yes - for table and model names, please follow Django naming conventions for models and table default names.  Should we start using Django naming conventions in future database designs to avoid confusion?

> 2. viaf_id is an integer field, but in previous projects we did them as URIs. This is probably obsoleted by the discussion of needing multiple urls for people anyway.

Let's keep it consistent with the other projects.  I think it's ok to treat it differently from other urls, since there may be extra behavior attached (i.e. pulling dates).  I remember @jabauer and I discussed the other urls, but I can't remember if we determined how we're going to handle them.  Perhaps we were going to use footnotes?

> 3. I assume title should be unrestricted and not a choice field.

Unrestricted sounds fine to me, but I'd defer to @jabauer if she has a different opinion.  I'm not certain what we're using this field for.  I just checked the personography and don't see any titles in fields, only miss/mr/mrs included in notes.  

> 4. For birth_year and death_year I used the AliasIntegerField class  and the DateRange mixin. This gets us validation with pre-existing code. It does mean that the table in the database will list start_year and end_year, but Django will know it as birth_year and death_year. Thoughts?

That's fine with me.  @jabauer any objections?

**Comment by jabauer** [comment]
Fine by me. And I will use Django model conventions in the schemas from now on to avoid confusion.

**Comment by bwhicks** [comment]
Great, thanks to you both, @rlskoeser and @jabauer. I've set up the VIAF id as a `django.models.UrlField()`, and the rest is as is.
