### ISSUE TITLE
As a content editor, I want to edit person information on the account page so I can associate multiple people and edit basic person information from the account.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#63]
- make person an inline on the account edit page
-currently thinking we should keep the autocomplete to allow associating with an existing person; update help text to indicate the form should be saved after changing

**Comment by bwhicks** [comment]
This issue has some unanticipated complications.

1)`People` is related by a M2M relationship as `persons`. Any inline has to use `Account.persons.through`. This does not allow access to `Person` fields, only the inline.
2) This could be mitigated by enabling the Django admin `show_change_link` and allowing an editable pop-up. (https://docs.djangoproject.com/en/2.0/ref/contrib/admin/#django.contrib.admin.InlineModelAdmin.show_change_link)
3) Grappelli does not currently support `show_change_link` . There is a pull request that would add this from August 2017, but no forward motion on it since (https://github.com/sehmaschine/django-grappelli/pull/819)

So our options are to rearchitect the database to use a foreign key on person to account (forgoing the autocomplete m2m for adding people) and have person appear only as an inline on account, or whether we should engage in some custom template work.

Either way, I think this changes the issue scope enough to refer it back to you @rlskoeser  before I invest significant time on it.

**Comment by elspethgreen** [comment]
Is this something you'd like us to weigh in on?  If so, I'm not sure I understand what the issue is!

**Comment by bwhicks** [comment]
@elspethgreen I don't think so quite yet. I'd like to get feedback from the dev team looking at this together before referring it to the project team. Thank you for checking though.

**Comment by rlskoeser** [comment]
@bwhicks thanks for looking into this.  I did a little more investigating, and there really is not a good way to support this.

@elspethgreen to explain a bit more: the Django admin interface gives us a lot of editing capabilities pretty easily, but it does (of course) have some limitations.  One of them is that we can't support the functionality we proposed for this feature because of the way the database is structured (and I'm sorry I forgot about that when we discussed it!).  However, we don't want to revise the database structure just because of that, since the data model was designed to capture how people and accounts interacted and related within Beach's library.

Since there isn't a good way to provide this feature, I propose we drop this one and implement #56 instead.

**Comment by elspethgreen** [comment]
That sounds good to me!  56 involves, as I understand it, being able to associate a person with an account and then "click" (or something) that associated person and get to their personography record.  (It would be great to go the other way too, for general flexibility, but less crucial for workflow.)  

The one thing I would like to keep from this is the ability to associate an account with multiple people.  Is that still possible?

**Comment by rlskoeser** [comment]
@elspethgreen yes - my plan is to keep the existing autocomplete on the account, which lets you associate multiple people, but add links near the input so that you can easily get from the account page to the person edit pages.

Preference question: do you want the link open in a new tab?  (It's generally not my preference to do that, but I could see it might make sense here.)

When I work on #60 I'll see if I can add a link to the account edit page.

**Comment by rlskoeser** [comment]
Closing this as a "won't fix" since it's not actually feasible.  Hopefully #56 will be sufficient.
