### ISSUE TITLE
Book search not working effectively.

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#630]
A search for "portrait of artist" yields strange results. See screen shot.
<img width="1070" alt="Screen Shot 2020-05-19 at 8 29 06 PM" src="https://user-images.githubusercontent.com/12616674/82393051-5fc4a380-9a13-11ea-8ac6-4304f3396776.png">

**Comment by rlskoeser** [comment]
Aha. The text field we're using to boost unstemmed matches has a stop word filter configured  but the list is empty. We're using an English stop word filter for the other version of the field.

I think the lack of filtering + field boosting explains the behavior.

I think it might make more sense to create and use an unstemmed text field for title and notes rather than adding a stop word filter to the general text field, which we're using for names.

@thatbudakguy any comments?

@jkotin sound ok?

**Comment by jkotin** [comment]
I can't quite play out in my head the effect of using an unstemmed text field v. adding a stop word filter.   But I defer to you here!

**Comment by rlskoeser** [comment]
@jkotin fair! I'm concerned about introducing unanticipated changes to a field we're already using for other things. I _think_ we had two variants of the field so we could boost unstemmed matches over stemmed ones, and if that's the case we probably want the two variants to be the same except for stemming.

@jkotin do you _want_ to support searching on stop words? if we do, we can still include that variant of indexing and decrease the boosting significantly.

**Comment by jkotin** [comment]
@rlskoeser I'm not certain. But there are some titles that might be mostly stop words, e.g. One of Us, One of Ours.  I'd have to think harder to get a better list.  There are also some stemmed matches that would be helpful to have, e.g. Russia/Russians.  (Is that how stemmed matches work?) How does the PUL catalog do it?  I've always been impressed by its search results.

**Comment by thatbudakguy** [comment]
> I think it might make more sense to create and use an unstemmed text field for title and notes rather than adding a stop word filter to the general text field, which we're using for names.

this definitely sounds right since we don't want to mess up the field type getting used for other purposes.

**Comment by rlskoeser** [comment]
FYI, slightly relieved to discover — the particularly bad behavior with "of" is because that occurs in so many author names and we have author names boosted very highly. I have an improved configuration I hope to deliver for testing soon that we can put in a hotfix release, but at least this isn't happening with all stopwords.

**Comment by rlskoeser** [comment]
@clmahoney please test the book search to see how it behaves. It should still be possible to search on stopwords like "the" and "of", but they should be deprioritized and not take precedence over other terms the way they were before. Searches on authors should still be more relevant than titles, and unstemmed matches should take precedence over stemmed matches.

**Comment by clmahoney** [comment]
- YES, this seems to behave well. I searched "portrait of artist" and the top two results were "Portrait of an Artist as a Young Dog" and "Portrait of the Artist as a Young Man". I also searched "letters dickinson" and I got the results I wanted. I searched around for other things and I think this is working fine. I'll leave this for @jkotin to check too.
