### ISSUE TITLE
Design // font of letter "e" with accent circonflexe

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#669]
Not urgent. See the font of the "ê" in the screen shot -- in "James Joyce Par Lui-même":

<img width="1048" alt="Screen Shot 2020-06-16 at 3 23 07 PM" src="https://user-images.githubusercontent.com/12616674/84819407-ed30ee80-afe5-11ea-8a8a-04188b8be4f2.png">

**Comment by rlskoeser** [comment]
If it's not displaying correctly, it likely means that glyph is not included in our font — although that seems surprising.

I just checked and it looks correct to me on Chrome and Firefox — only on Safari do I see this version.

**Comment by rlskoeser** [comment]
@jkotin could you or @clmahoney re-input the character to make sure it's the standard character we expect rather than a different variant that was cut and paste in? 

Also, in future: if there is a link on the public site where we can easily view or duplicate the problem, please include the url along with any screenshots.

**Comment by jkotin** [comment]
That fixed it!  It was a cut and paste job.

And will do about links!
