### ISSUE TITLE
We represent deposit reimbursements, but not deposits on the website.

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#675]
When a member joined the lending library, they paid a membership fee and a deposit. For example, 25f (fee) and 50f (deposit). On the website, we represent that event under “Activities / Membership” as a “subscription” and list the fee under "amount." We do not list the deposit.

When a member ended their membership, they received their deposit back. On the website, we represent that event under “Activities / Membership” as a “reimbursement” and list the reimbursed deposit under “amount.”

The result is a discrepancy between what “amount” means on the website.

An example: consider de la Grandville:

https://shakespeareandco.princeton.edu/members/geadeville/membership/

The membership activities information makes it seem as though de la Grandville received back more than they paid.

Two solutions: 1/ we could re-design the “Activities / Membership” page to show both the fee amount and the deposit amount; or 2/ include the deposit as a separate line, so de le Grandville would be shown as paying 25f for a subscription, 50f for a deposit, and receiving 50f as a reimbursement.

A partial solution—but perhaps adequate: we list both the fee amount and the deposit amount under "amount" as a single sum.  If we adopt this solution, de le Grandville would be shown as paying 75f for the subscription (fee + deposit) and receiving 50f as a reimbursement.

**Comment by rlskoeser** [comment]
@jkotin I would like to go with the last option — include deposit in the total amount displayed.

**Comment by jkotin** [comment]
OK, that's fine with me. Could that fix be included in the next iteration? I'm happy to accept it as the best solution under current circumstances. But do you think it's the ideal solution?  I.e. should we keep having a separate way to represent deposits as a wishlist item?

**Comment by rlskoeser** [comment]
Yes, this approach should be a simple fix we can do quickly, which is why I'd like to go with that option.

I think we're unlikely to revise the design of that table given all the possible things we could be working on. It seems like a reasonable solution to me; people interested in digging into how the financials worked should probably be looking at the data exports anyway.

**Comment by jkotin** [comment]
I agree with everything you say.

I do think there's value in keeping a wishlist of changes that we know we'll never prioritize.  Maybe the next generation of the team will think differently!

**Comment by rlskoeser** [comment]
It's fine with me if you want to make a wishlist item for a better solution!

**Comment by rlskoeser** [comment]
@jkotin please review on the test site to confirm subscription amount = deposit + price paid.

**Comment by jkotin** [comment]
@i-davis would you spot check 10 random subscriptions on the test site and let us know here if the amounts look right?

**Comment by i-davis** [comment]
@jkotin @rlskoeser: I spot-checked 10 random subscriptions. 8 of them looked fine. 2 looked questionable.

I think the problem is that any amount other than a franc is not calculated.

Henri Regnier subscribes with a deposit of 5.60 and a fee of 4. The test site displays his "Amount" as 9f.
Denise Ullman subscribes with a deposit of 11.20 and a fee of 6.40. The test site displays her Amount as 17f.

So: anything after the decimal isn't counted in the final "Amount", I think?

**Comment by rlskoeser** [comment]
This looks like a python integer vs. floating point addition problem! Good catch @i-davis, I'll revisit.

**Comment by rlskoeser** [comment]
@jkotin @i-davis fix available on the test site for review

**Comment by jkotin** [comment]
@i-davis would you check this out?

**Comment by i-davis** [comment]
@jkotin @rlskoeser: looks great!
