### ISSUE TITLE
As a data editor or dataset user, I want all source citations for all events so that I can tell which ones came from logbooks, address books, or cards.

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#702]
## notes for testing
- confirm events with 36ADD and P36ADD have footnotes added linking to the correct address book
- confirm events from address book that already have footnotes still only have one footnote (no second note added)
- confirm events from logbooks have footnotes linking to the logbook
- check source type in [test data export](https://drive.google.com/drive/u/0/folders/15JuzOXQ5DcvcgZEcQQB_nO_Uz-f8F1lL); all events should now have source types (maybe do some faceting in OpenRefine to review)
- go to the footnotes list view, open a newly created footnote for logbook or address book, click on the history button (top right), and check that there is a log entry documenting that the footnote was created by a script

----
Subscription events from the address books are tagged:

36ADD: the 1936 address book
P36ADD: the post-1936 address book

The logbooks don't have tags.

## dev notes
Create new data migration to do the following:
- [x] get references to bibliography entries for 1936 address book, post-1936 address book, and generic logbook entry
- [x] find all events with tag 36ADD (but not P36ADD) and create a footnote associating that event with the 1936 address book
- [x] find all events with tag P36ADD and create a footnote associating that event with the post-1936 address book
- [x] find all remaining events without any footnote and associate with the generic logbook
- [x] for all footnotes, create django admin log entry documenting that the footnote was created by script

**Comment by rlskoeser** [comment]
Based on the large number of dates where the logbooks overlap and the impossibility of determining which events were documented in which particular logbook, we will use a generic logbook bibliographic note for all events from the logbooks.

**Comment by rlskoeser** [comment]
@jkotin It occurred to me I'd better clarify: which events exactly do you want included in this update? The issue specifies "subscription events" — did you have a particular set of event types in mind? I'm wondering if we can just apply this to all events without footnotes, since we expect every event from a card to have a footnote already by the time we run this?

**Comment by jkotin** [comment]
Yes, all events without footnotes.

All the non-subscription events (i.e. borrow, crossed out, generic, gift, loan, periodical subscription, purchase, request) should already have footnotes with references to specific cards. Only subscription, renewal, supplement, reimbursement, and other should get footnotes.

Does this seem right to you, @i-davis ?

**Comment by i-davis** [comment]
Yes, seems right to me, @jkotin!

**Comment by kmcelwee** [comment]
Would someone mind adding me as an admin? My netid is `kmcelwee`. I was working off SQL queries on a production dump, but obviously the UI makes things easier. I gave myself permission already on the test site. 

Here's where I left off @rlskoeser, hopefully it's somewhat useful! I imagine some of this is heavy handed, so please definitely tag me on whatever you end up doing. I get the sense that there may be a proper django way to do some of this.

```python
from mep.footnotes.models import Bibliography
from mep.accounts.models import Subscription
from string import punctuation

# Get logbook and address book IDs
BIB_ID_36ADD = 649
BIB_ID_P36ADD = 655
BIB_ID_GENERIC = 654

bib_36add = Bibliography.objects.get(pk=BIB_ID_36ADD)
bib_p36add = Bibliography.objects.get(pk=BIB_ID_P36ADD)
bib_generic = Bibliography.objects.get(pk=BIB_ID_GENERIC)

# Ensure that the IDs were connected to the expected bibliographies
assert "Address Book 1919–1935" in str(bib_36add)
assert "Address Book 1935–1937" in str(bib_p36add)
assert "Logbooks 1919–1941" in str(bib_generic)

def tokenize(notes):
     # Tokenize notes into lowercase words stripped
     # of punctuation and whitespace 
     # (some tags end in colons or commas)
     return [word.strip(punctuation + ' ').lower() 
                    for word in notes.split()]


# Get all the required events that need footnotes. 
# The four groups that need to have footnotes applied:
# {'Other', 'Subscription', 'Renewal', 'Supplement'}
# make up the subset of the "Subscription" class

subscriptions = Subscription.objects.all()

# divide up the subscriptions by tag
subs_36add = []
subs_p36add = []
subs_generic = []
for sub in subscriptions:
     tokenized_notes = tokenize(sub.notes)
     if '36add' in tokenized_notes:
          subs_36add.append(sub)
     elif 'p36add' in tokenized_notes:
          subs_p36add.append(sub)
     else:
          subs_generic.append(sub)

# then somehow connect the bibliography to the event?
# I assume that's straightforward?
```

And since you probably need the latest mysql dump:

```shell
scp deploy@libservdhc7:/home/deploy/production_dumps/2020-12-##-mepprod.sql .
```

**Comment by rlskoeser** [comment]
@i-davis @jkotin I want to make sure I'm connecting the tags with the correct bibliographic entry: does 36ADD correspond to "Address Book 1919–1935" or "Address Book 1935–1937" ?

**Comment by i-davis** [comment]
@rlskoeser : Address Book 1919-1935! We were referring to that one as the 1936 address book, and the other as the post-1936 address book. (P36ADD means post-1936.)

**Comment by rlskoeser** [comment]
Thank you for clarifying @i-davis ! I couldn't remember if P meant pre or post, and 1936 is ambiguous based on the dates in the entries.

**Comment by i-davis** [comment]
Yeah, totally, @rlskoeser! Really, it's the most confusing naming system...

**Comment by rlskoeser** [comment]
@kmcelwee thanks for making an attempt to start this issue and for sharing your notes. I keep forgetting how new you are to django! If you haven't already, please read about django migrations at some point: https://docs.djangoproject.com/en/3.1/topics/migrations/ 

I tagged you on the pull request, so you can take a look at my solution for this — feel free to ask questions when you get the chance to review. It was a little complicated, because footnotes and admin log entries are both implemented with a generic foreign key (see https://docs.djangoproject.com/en/3.1/ref/contrib/contenttypes/#generic-relations ), and the convenience relationships we use for those in regular code aren't available in migrations.

**Comment by i-davis** [comment]
All the footnotes look good to me, @rlskoeser!

**Comment by rlskoeser** [comment]
Closing based on @i-davis' testing.
