### ISSUE TITLE
Updated data exports to include source type or footnote to specific source

### ISSUE THREAD

**Issue by jkotin** [Princeton-CDH/mep-django#703]
## testing notes
Event data export now includes a `source_type` field. Spot check that it looks correct based on footnotes currently in the database. (NOTE: until the migration to add footnotes has been completed, we won't have source type for logbook events and address book events based on tags)

---
When we update the data exports, the events dataset should have a information about the source type and/or specific source for each subscription event.

## dev notes
Update the `export_events` manage command in the `accounts` app
- [x] add `source_type` to the list of csv fields, before `source_citation`
- [x] modify the `source_info` method to include the `bibliography.source_type.name` as `source_type`
- [x] update the unit test for the source info method to confirm that it's included as expected

**Comment by kmcelwee** [comment]
Changed point estimate from 1 -> 0 because updates were more trivial than expected, per conversation in https://github.com/Princeton-CDH/mep-django/issues/703

**Comment by rlskoeser** [comment]
@i-davis test event data export in drive here: https://drive.google.com/drive/u/0/folders/15JuzOXQ5DcvcgZEcQQB_nO_Uz-f8F1lL 

Please confirm that the event export now includes a source type field, and that the source type is set correctly for the items that have sources (= footnotes in the db). Note that it won't be populated for everything yet because we haven't run the data migration that will add footnotes for address books and logbooks based on tags.

**Comment by i-davis** [comment]
Looks good to me, @rlskoeser!
