### ISSUE TITLE
upgrade to most recent versions of django + wagtail

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#788]
Develop branch has already been partially updated so we're no longer as far behind as we were (this work was tracked on #752), but we should update the code to get it running against the most recent versions of django, wagtail, and python.

Develop is currently on wagtail 2.16, django 3.2, and python 3.9.  We'll want to test against newer versions of python and update that as well, but we can't install anything newer than 3.8 until we're migrated to newer PUL VMs (which is in progress).

The wagtail release list includes compatibility with python and django versions: https://docs.wagtail.org/en/stable/releases/upgrading.html 

Django has great documentation on how to upgrade: 
https://docs.djangoproject.com/en/4.2/howto/upgrade-version/

Wagtail 5.0 is not compatible with django 4.1, so upgrade strategy should be as follows:
- upgrade wagtail one major or minor version at a time to 4.2
- upgrade django one major or minor version at a time to 4.1
- upgrade wagtail to newest version we can
- upgrade django to the newest version we can 

wagtail 3.0 has an api change that messes up some of our paths, but if you look at the release notes you'll see there's a script included that will make the necessary changes

mep depends on djiffy, so it looks like this upgrade will be blocked until we get that updated first . 
djiffy depends on piffle and both of them depend on `attrmap`, which is not being maintained and not available in newer versions of python; they'll both need to be updated to address that dependency. I've already tackled that once with parasolr and was able to get everything working with the `addict` library instead, so hopefully we can follow the same path.

relevant tasks:
- https://github.com/Princeton-CDH/djiffy/issues/14 
- https://github.com/Princeton-CDH/piffle/issues/10

**Comment by quadrismegistus** [comment]
Ok, we've got the fixture loading problem solved, now working through other failures.

Hunting through one now, keeping notes:

* This is the error I'm getting in the tests, versions of this:
![Screenshot 2023-11-13 at 4 01 44 PM](https://github.com/Princeton-CDH/mep-django/assets/733853/1ff33640-b622-4b30-b11c-e99f260d7f89)

* It looks like that function expects UploadedDocument to be a subtype of Page, but instead UploadedDocument is a subtype of Model and doesn't have methods like creatable_subpage_models. 

* From the docs for UploadedDocument it looks like that class is used for _partial_ document creations?
![Screenshot 2023-11-13 at 4 09 06 PM](https://github.com/Princeton-CDH/mep-django/assets/733853/79400648-b690-4e35-a5b3-d8779b44cf83)

* That may make sense now given a _warning_ I'm getting in wagtail:

```
mep/pages/tests/test_pages_models.py::TestHomePage::test_can_create
  /Users/ryanheuser/github/mep-django/venv/lib/python3.8/site-packages/wagtail/query.py:552: RuntimeWarning: Specific versions of the following items could not be found. This is most likely because a database migration has removed the relevant table or record since the item was created:
  [{'id': 2, 'title': 'Shakespeare & Company Project', 'type': <ContentType: wagtaildocs | uploaded document>}]
    warnings.warn(
```

* That document in the wagtail_pages.json fixture looks like this:

```
Ok, we've got the fixture loading problem solved, now working through other failures.

Hunting through one now, keeping notes:

* This is the error I'm getting in the tests, versions of this:
![Screenshot 2023-11-13 at 4 01 44 PM](https://github.com/Princeton-CDH/mep-django/assets/733853/1ff33640-b622-4b30-b11c-e99f260d7f89)

* It looks like that function expects UploadedDocument to be a subtype of Page, but instead UploadedDocument is a subtype of Model and doesn't have methods like creatable_subpage_models. 

* From the docs for UploadedDocument it looks like that class is used for _partial_ document creations?
![Screenshot 2023-11-13 at 4 09 06 PM](https://github.com/Princeton-CDH/mep-django/assets/733853/79400648-b690-4e35-a5b3-d8779b44cf83)

* That may make sense now given a _warning_ I'm getting in wagtail:

```
mep/pages/tests/test_pages_models.py::TestHomePage::test_can_create
  /Users/ryanheuser/github/mep-django/venv/lib/python3.8/site-packages/wagtail/query.py:552: RuntimeWarning: Specific versions of the following items could not be found. This is most likely because a database migration has removed the relevant table or record since the item was created:
  [{'id': 2, 'title': 'Shakespeare & Company Project', 'type': <ContentType: wagtaildocs | uploaded document>}]
    warnings.warn(
```

* Here is that document:

```
{
    "model": "wagtailcore.page",
    "pk": 2,
    "fields": {
        "path": "00010001",
        "depth": 2,
        "numchild": 3,
        "translation_key": "304187a7-03ed-43b8-a8a5-8a291d7d7284",
        "locale": 1,
        "latest_revision": null,
        "live": true,
        "has_unpublished_changes": false,
        "first_published_at": null,
        "last_published_at": null,
        "live_revision": null,
        "go_live_at": null,
        "expire_at": null,
        "expired": false,
        "locked": false,
        "locked_at": null,
        "locked_by": null,
        "title": "Shakespeare & Company Project",
        "draft_title": "Shakespeare & Company Project",
        "slug": "home",
        "content_type": 70,
        "url_path": "/home/",
        "owner": null,
        "seo_title": "",
        "show_in_menus": true,
        "search_description": "",
        "latest_revision_created_at": null,
        "alias_of": null
    }
},
```

I wonder why it's still considered partial? I already used the migrations to change the fixture json so that it can be loaded. Now I guess it's loading but not sufficiently to avoid UploadedDocument replacing a Document.

* But now that I think about it, a Document would also not have the attribute we're expecting. Document subclasses AbstractDocument, UploadedDocument subclasses Model, but neither Page.

* Sorry to ramble, just puzzling this through...

**Comment by jkotin** [comment]
This looks good so far. Anything specific I should test?

**Comment by jkotin** [comment]
It looks good to me!  I made some new pages, and created some new members. Everything worked well.
