### ISSUE TITLE
As a content editor, I want to view and edit subscription purchase date separate from start and end date so that start and end dates accurately reflect the membership period.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#80]
## testing notes
- in admin, subscriptions should now have purchase date in addition to start and end dates
- you should be able to view & edit subscription purchase date as a partial date 
- you should be able to view & edit subscription purchase date when editing a subscription inline with an account
- purchase date should be set based on subscription start date; if subscription start was partial, purchase date should be too
- check renewals that previously overlapped with a preceding subscription: start and end date should have been adjusted so they _follow_ the preceding subscription period
- event data export should include subscription purchase dates ([test export in drive](https://drive.google.com/drive/u/0/folders/1n-ggARzppfg3nm18QkKijMewdbjH_SD6))

## dev notes
Per @jkotin https://github.com/Princeton-CDH/mep-django/issues/79#issuecomment-378789437 :
> ... we need to account for renewals that occur before the previous renewal or subscription has expired.

> E.g., see the file for Bobby Baker.  She renewed on 9/6/20 for three months, and then renewed for one month on 11/19/20.  Her subscription should end on 1/6/21, not 12/19/20 as the personography currently indicates.

To address this:
- [x] subscription data model needs a new field for purchase date independent of subscription start date
- [x] purchase date needs to be made editable on the admin edit forms for subscription event and subscription inline on accounts
- [x] for all subscriptions, populate purchase date from start date (according to @elspethgreen there are exceptions, but they are rare and should be corrected manually after this change is made)
- [x] for all renewals, what is currently recorded as subscription start date to purchase date, calculate actual start date based on the end of the previous subscription date, and recalculate subscription end date based on corrected start date and duration
- [x] add subscription purchase date to event export

**Comment by rlskoeser** [comment]
@jkotin @elspethgreen it's not clear to me how soon this needs to be fixed - what is the impact for you at this point?

I think this change might suggest some related date auto-population and validation you would want added for editing subscriptions and renewals, but I'm not sure how simple it will be.  How much are you still adding new subscription renewals?  Can this data migration wait until all known logbook data is entered so that we can convert everything at once and only implement validation on the form without worrying about auto-populating dates?

**Comment by jkotin** [comment]
Let's discuss at our meeting on 4/11. J

**Comment by elspethgreen** [comment]
An update: I'm looking through some of the data, and noticing many instances of explicitly designated differences between renewal and purchase date.  The actual renewal period has usually been recorded in notes, and the "duration" left blank.  These will be relatively easy to find and correct once the database can accommodate the information.  But what will the process be for the more standard renewals?  Will we be able to auto-correct this based on the sequence of subscriptions and renewals in a given person's timeline?

**Comment by elspethgreen** [comment]
This is definitely not pressing, just wondering how it will go when we proceed!  The logbook data is all inputted at this time.

**Comment by rlskoeser** [comment]
@elspethgreen can you provide some examples? I was expecting we would be able to auto-correct the dates based on previous subscriptions and renewals, but if the renewal duration is in a notes field that will be hard.

**Comment by elspethgreen** [comment]
An example of an explicitly designated non-purchase-date renewal period is in Bienenfeld's subscription on October 9.  The encoder has put in the notes that the subscription actually runs from Sept 29 - Oct 29.  I initially found these by looking at subscription events that have no duration; I suspect that all of the events thus-encoded will also have no duration, since the encoder could not represent it properly in the current system.

Would it be possible to pull up a txt list of all of the subscriptions with no duration, including their notes fields?  It's taking me a while to click through each one, and I could eyeball a list more quickly and pick out the ones that had date info in their notes fields.

**Comment by rlskoeser** [comment]
@elspethgreen yes, I see the problem. There's no way to enter this in the current system! I think we should prioritize this for fixing sooner than later, since there is data work dependent on it.  Should we also include the beginning of the notes field on the list view?

We had planned some CSV exports in the next set of functionality, I'm starting to think it would be useful for you to have more of them than we'd initially discussed.  Think about which ones would be helpful for this kind of data work.

Do you still want the text list of subscriptions with no duration?

**Comment by rgmunson** [comment]
This would be better to do after the person merge data work is complete because then we will be able to calculate the subscription dates most accurately. @clmahoney keep us posted!

**Comment by rlskoeser** [comment]
No longer blocked by person merge data work.

**Comment by rlskoeser** [comment]
Simpler than expected (and well-planned and documented!); downgrading from 3 points to 2.

**Comment by rlskoeser** [comment]
@clmahoney I generated a [new test export of the events data](https://drive.google.com/drive/u/0/folders/1n-ggARzppfg3nm18QkKijMewdbjH_SD6) to help you with testing the adjusted start/end dates for renewals and so you can confirm that they now include subscription purchase dates.

**Comment by clmahoney** [comment]
- YES, I see in the admin that there is now a "purchase date" section and it is filled in if there was a subscription, a renewal, or a supplement on that date 
- YES, I can edit the purchase date to make it a partial date. Tried with only year, only year + month, and only month + date
- YES, I can edit the purchase date of a subscription (and also make it a partial date) in a member's account. Tried with Richard Aldington: 
![Screen Shot 2020-04-29 at 3 35 49 PM](https://user-images.githubusercontent.com/16673934/80638914-38d80a80-8a2f-11ea-83d3-5c53ec0c9914.png)
- YES, the purchase date always matches the subscription start date! Including if it's just a partial date. 
- YES, I checked on Alajouanine's subscription and renewal, that overlaps on the live admin/site. Then I checked her subscription and renewal on the test site, and how the renewal starts on the next day after the subscription ends. 
Live admin: 
![Screen Shot 2020-04-29 at 3 49 45 PM](https://user-images.githubusercontent.com/16673934/80640315-38d90a00-8a31-11ea-8700-7ed559b2d847.png)
Test admin: 
![Screen Shot 2020-04-29 at 3 50 15 PM](https://user-images.githubusercontent.com/16673934/80640325-3e365480-8a31-11ea-8ea7-89430fc19f9c.png)
HOWEVER: although the renewal start date changes, the purchase date for the renewal remains the same as it was, i.e. when the subscription date ends. This is the correct behavior, right? 
- YES, the CSV has the subscription purchase date included: 
![Screen Shot 2020-04-29 at 3 57 30 PM](https://user-images.githubusercontent.com/16673934/80640985-30cd9a00-8a32-11ea-9910-857eac8501f5.png)
and YES it's on JSON too!

**Comment by jkotin** [comment]
This looks great too.  Is there a way to see/check how the timelines have changed, based on the new calculations @rlskoeser ?

**Comment by rlskoeser** [comment]
@jkotin thanks for reminding me. I thought about this when I was working on the code changes but forgot to review after putting it on the test site.

I just compared the test and production member graphs and data tables, and there are slight differences in numbers in some places - but very slight, membership total by month that have changed are only 1 or 2 off from what they were before.

**Comment by rlskoeser** [comment]
@jkotin @clmahoney the comments above from @elspethgreen (back in April 2018 🙄 ) have some specifics on records that will need to be corrected after this work. Can you review to make sure you understand what needs to be done and that you'll be able to make these updates?

https://github.com/Princeton-CDH/mep-django/issues/80#issuecomment-382030538
https://github.com/Princeton-CDH/mep-django/issues/80#issuecomment-382932157

I looked at the Bienenfeld 10/9 subscription but I'm not sure I understand. Can a renewal be paid for _after_ the start date?

Ellie thought you'd be able to find subscriptions like this based on missing durations. Is the information included in the event export sufficient?

**Comment by jkotin** [comment]
@clmahoney would you work with @i-davis on this?  He knows the membership data the best. Let us know if you understand the data work that needs to be done, and how much time it will take.

**Comment by i-davis** [comment]
@rlskoeser @jkotin @clmahoney: So I think I understand the issue! Let me know if the following makes sense as a response. I'm toggling back and forth in my brain between the specific situation Ellie notes; and your question, @rlskoeser, about whether a renewal can be paid for after the start date. I'm just going to be over-thorough in what follows: forgive me if I'm telling you stuff you already know, and/or I've completely missed the point! (I didn't want to bug @clmahoney, given that her FPO's tomorrow!)

Just so we're all on the same page, this is my analysis. Tell me if it fits with yours? 

Longstanding members -- members who seemed reliable enough to SB, is maybe the way to put it -- often paid for a renewal on a different day than the renewal was due, whether before or after. Sometimes they pay only a day or five late or early. Sometimes they pay in a different month. I'd speculate that off-schedule payments are particularly common when a sub duration is higher than a couple months. Someone who is renewing for a year at a time can pay in July for a sub renewal due in April, and so forth.

The problem: for the most part, information about whether a payment is off-schedule is _not_ included in the logbooks. 

The Bienenfeld example (1940-10-09) Ellie points out is an outlier: I think it's rare that a logbook notes the precise dates a sub is for, like that:

<img width="513" alt="Screen Shot 2020-04-30 at 12 20 32 PM" src="https://user-images.githubusercontent.com/15250325/80736025-91ff7700-8adf-11ea-9112-ec9bbc37932f.png">

This is actually a good thing, right? It means that the correction work Ellie was worried about will be minor: there aren't many examples like this to fix.

What's more common, and what I understand you all to be working to fix, is this: You can semi-accurately track the actual days of a sub duration by analyzing a person's sub pattern. 

Here's a common situation that I think might present us with problems. Tell me if you think that's the case! 

The problem is what you suggest in your question, @rlskoeser: a renewal does not _overlap_ with a previous subscription; instead, the sub was renewed _late_. The following screenshot is for a renewal for Pagliano recorded the day before (1940-10-08) Ellie's Bienenfeld example. 

<img width="404" alt="Screen Shot 2020-04-30 at 12 22 30 PM" src="https://user-images.githubusercontent.com/15250325/80736113-ab082800-8adf-11ea-8583-4487c4d0aaaa.png">

If you go into the database, Pagliano's previous subscription looks like it lasted until 1940-10-19: Pagliano seems to be renewing 11 days early. But then if you look at the subscription before that one, you see that Pagliano was renewing on April 19 for a sub that ran out on April 2nd: he was 17 days late, in other words, on April 19.

<img width="232" alt="Screen Shot 2020-04-30 at 12 31 10 PM" src="https://user-images.githubusercontent.com/15250325/80736147-b65b5380-8adf-11ea-8747-62a8095ff528.png">

We've recorded the April 19 sub as lasting from April 19 to October 19. And we've recorded the October 8th sub as lasting from 8 October 1940 to 8 April 1941. But if you take the sub date of the first renewal on Pagliano's account, for 2 April 1940, then all the subscriptions should last from the 2nd of the start month to the 2nd of the end month. And the subscription on October 8th was actually 6 days late. 

But then, of course, we don't actually have the subscription info for Pagliano's _initial_ subscription, we only have renewal information! So if the April 2 renewal was itself early or late, then we really don't know the subscription schedule -- and we likely have no way to trace what the actual subscription schedule was, because it was rare that SB & co. kept records of that schedule.

You can trace some of this better on certain cards. See Cyrille Arvanon's card, s2, recording a renewal that technically starts on May 19, but which he seems to have paid for on July 1 -- _despite having been in the store on May 20_. SB seems to have let him slide on the renewal for a full 40 days.

<img width="433" alt="Screen Shot 2020-04-30 at 12 38 16 PM" src="https://user-images.githubusercontent.com/15250325/80736268-e30f6b00-8adf-11ea-84c6-8f91083929f1.png">

My speculation would be that such belated renewals are actually quite common. The difficulty is sorting out when a renewal is belated, and when a person has actually let a subscription lapse. Arvanon's next renewal, for instance, is on December 24, and is clearly not a late renewal, but a resubscription after a lapsed sub: the last sub is on September 24, and the subscription is clearly noted as lasting from 24 December 1938 to 24 June 1939, as restarting on the purchase date, in other words.

<img width="419" alt="Screen Shot 2020-04-30 at 12 58 28 PM" src="https://user-images.githubusercontent.com/15250325/80737969-51552d00-8ae2-11ea-9685-98ab220d94c9.png">

Does this all make sense? Is it a good response to the questions you're posing, have I understood them right? If so, does it seem like an accurate analysis?

**Comment by jkotin** [comment]
@i-davis thank you for this.  I'm going to wait on a full response until I hear what @rlskoeser thinks.  I hadn't ever consider the following scenario (scenario 1):

John Smith joins on 5/1/20 for one month, renews on 6/5/20 for one month, and renews again on 7/3/20 for one month.  What is the correct membership timeline? 5/1/20 to 8/1/20 or 5/1/20 to 8/3/20?  I'm not sure we can know.

Whereas, we want to be sure that if Jane Smith joins on 5/1/20 for one month and renews on 5/25/20 for one month, her membership timeline is 5/1/20 to 7/1/20. (Scenario 2.)

I guess what's important to know now: what datawork remains to be done (likely by Ian) and have we created problems by not thinking about scenario 1.  (Or perhaps only I did not think about scenario 1.)

**Comment by rlskoeser** [comment]
Yes, @i-davis thanks for investigating this so thoroughly. 

I also had not considered scenario 1! I agree, it's not clear we can determine for sure what the correct membership timeline is — which indicates to me that looking through the records and revising those dates should be handled manually (e.g., those rare cases where the notes tell us exactly what the dates were). 

Scenario 2 seems pretty clear — if the renewal happened before the previous subscription, the next period should continue _after_ the first one. This is the logic I've implemented.

However: seeing the clear dates in Josh's example (5/1 to 7/1) makes me think I might not have calculated the shifted durations correctly. I used the duration of the subscription in **days** and applied it to the shifted start date, when I probably should have used **months**. I don't know how much of an impact this has or how many records are affected. Is it acceptable to clean this up after the migration runs in production?

@jkotin I also set the next subscription period to start the day after the first one ends; should it start the same day?

**Comment by rlskoeser** [comment]
@jkotin I just queried my local dev database to get a sense of scale and my query only found 13 records where the purchase date doesn't match the start date. That's much lower than I expected, and seems like not a big deal to adjust the dates if needed. I think the more important functionality is splitting out the purchase date so you can enter them properly.

**Comment by jkotin** [comment]
@rlskoeser I do think months is right, not days, and that it's OK to clean up in production.  @i-davis would you let us know if you agree months v. days.

Re: same day v. day after.  I think same day is right, but I'd also like to hear what @i-davis thinks. I'm less sure of this.

**Comment by jkotin** [comment]
@rlskoeser would you clarify re: "only found 13 records where the purchase date doesn't match the start date"? Is that only 13 examples of scenario 2?  I also had expected many more!

We should also remember -- as @i-davis knows well! -- that there is often a slight discrepancy between renewal dates on the cards and in the logbooks. My sense is that the dates in the logbooks are accurate -- that's when the member visited the shop and renewed the membership -- but that Beach often adjusted the dates when she wrote them on the cards to match the timeline. Stein is an example of this, if I remember correctly.

It's inevitable and even apt that the timelines are approx.  We just want to continue to be as faithful to Beach as possible.

**Comment by i-davis** [comment]
@rlskoeser @jkotin : 

I agree re months over days!

& I'd vote same day, if I'm understanding correctly: subs go 1/1 to 2/1, then 2/1 to 3/1, then 3/1 to 4/1, and so on. Is that what you mean?

**Comment by i-davis** [comment]
@jkotin -- I'm wondering if I was clear enough about the problem with not being able to tell the difference between a lapsed subscription and a belated renewal, and why that matters. Sorry to go on, especially if you already knew this and I was overexplaining in the first place!

The first Arnavon example is a belated renewal, where Arnavon purchases a renewal a full 40 days after her last subscription ended, but the renewal starts on the same day the last subscription ended. This is because she continued to borrow books even when she hadn't paid for the renewal yet.

The second Arnavon example is a lapsed subscription, where the renewal starts on the day the renewal is purchased. Arnavon hadn't been borrowing in between the end of her last subscription and the beginning of her renewal, so she got to restart.

In other words, I think scenario 1 is quite common, and that sometimes the gaps between the end of the last subscription and the purchase of the renewal can be quite far apart. And in many cases, we can't actually know if the renewal purchase counts as a lapsed subscription or a belated renewal.

Pagliano could be an extreme example of scenario 1, a series of belated renewals. I could imagine that Beach would have adjusted Pagliano's dates on their card, as with Stein. In other words, the subscription info we have in the database goes:
![](https://user-images.githubusercontent.com/15250325/80736147-b65b5380-8adf-11ea-8747-62a8095ff528.png)

But I think it possible that Beach may have adjusted Pagliano's dates to be always 2 April to 2 October and 2 October to 2 April on their card, however. In other words, that last subscription, which we have in the database from 9 Dec 1941 to 9 June 1942, could actually, for Beach, have counted as 2 October 1941 to 2 April 1942 on Pagliano's card. 

The question is whether Pagliano was still borrowing books continuously, or if they had stopped borrowing books. Which we can't know, since we don't have Pagliano's card.

I'm with you that the timelines will always be approximate!

**Comment by rlskoeser** [comment]
@jkotin the 13 number was based on a query I ran to check for subscriptions where the purchase date didn't match the subscription start date — meaning the data migration adjusted the start date. It seems likely there probably are more of subscriptions that should be adjusted, but apparently not very many that my code could identify and adjust. 

@i-davis thank you for the helpful terminology! Lapsed subscription vs belated renewal. 

I don't know of an easy way to identify those automatically, and the code I wrote only deals with _early_ renewals. 

I'm going to go ahead and close this issue — Josh previously signed off on it, and the code has already been released.

I can generate a new event export to help investigating these subscriptions so you can figure out what updates need to be made.
