### ISSUE TITLE
As a content editor, I want to view and edit borrowing events so that I can review data imported from the cards and correct any errors.

### ISSUE THREAD

**Issue by rlskoeser** [Princeton-CDH/mep-django#90]
## Notes for testing
- [ ] search and browse borrowing events created by the import
- [ ] edit and save changes
- [ ] create a new borrowing event
- [ ] view and edit footnote created by the import, documenting source of the borrowing event

## Notes for development
Should include footnotes as an inline, to display source once #88 is implemented.

**Comment by elspethgreen** [comment]
I decided to say that he'd borrowed "Portrait of the Artist," and came across something that might be problematic.  I get a list of all of the items" with "portrait" in them, and it includes some variants that must have been given their own item status--this in itself is fine, the undergrads are going to clean this up.  But the problem is that I actually can't easily tell which is the "canonical" record (with "Portrait," I can make an educated guess, because I'm pretty sure I know the full standard title, but for another book like "Sackville Street" it would be harder).  I wonder if including the borrow-count in parenthesis after each of the items might be a quick semi-solution to this?

**Comment by elspethgreen** [comment]
@clmahoney This one's kinda fun to play around with!  Just go to the list of borrowing events and click on a random one, then check it against the image file in the footnote to make sure it's correct.  You can edit dates etc. as well.  Try adding a new borrowing event and see what happens--I have some issues that I documented above, and I'd be interested in your experience.

**Comment by rlskoeser** [comment]
@elspethgreen regarding this:
> A potential weirdness--when trying to add a borrowing event, I typed in "hemingway" for the account. The search suggestions display Hemingway's account 8 times, even though it is the same account each time (433). This isn't necessarily a problem, it's just strange and might reflect something deeper going on.

That sounds to me like something we should fix.  It should be a simple fix.  I assume this behavior happens every time you search for an account from the event edit page?  (Although perhaps you're not using that much, since we adjusted most other events to be edited from the account page.)

**Comment by rlskoeser** [comment]
Updated so you should now see only one copy of each account in the autocomplete list.

**Comment by elspethgreen** [comment]
This looks good now!
